import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const directory = await mkdtemp(join(tmpdir(), 'plowshare-admin-ui-'));
const fixture = await protocolFixture({ setup: true, serverAdmin: true, rotateTokens: true });
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: directory, PLOWSHARE_DESKTOP_PROFILE: join(directory, 'profile') };
delete env.ELECTRON_RUN_AS_NODE; delete env.PLOWSHARE_DESKTOP_CONFIG;
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const page = await app.firstWindow();
  await page.locator('#connection-button').waitFor();
  await page.locator('#connect-sidebar').click();
  await page.locator('#server-url').fill(fixture.base);
  await page.locator('#connection-form details summary').click();
  await page.locator('#setup-temporary').fill('fixture-temporary');
  await page.locator('#setup-handle').fill('fixture');
  for (const id of ['setup-password', 'setup-repeat']) {
    const input = page.locator('#' + id);
    // Electron's secure inputs can race insertText after changing focus on macOS.
    await input.click();
    await input.pressSequentially('fixture-password', { delay: 30 });
    await expect(input).toHaveValue('fixture-password');
  }
  await page.screenshot({ path: '/tmp/plowshare-admin-setup-ui.png' });
  assert.equal(await page.evaluate(() => document.querySelector('#setup-password').value === document.querySelector('#setup-repeat').value), true, 'Entered passwords differ before click');
  await page.locator('#server-setup').click();
  await expect(page.locator('#connection-dialog')).toBeHidden();
  await expect(page.locator('#server-project-add')).toBeVisible();
  const saved = JSON.parse(await readFile(join(directory, 'desktop-connection.json'), 'utf8'));
  assert.equal(saved.account, 'fixture');
  await page.locator('#server-project-add').click();
  await page.locator('#server-project-name').fill('Server example');
  await page.locator('#server-project-workspace').fill('/srv/projects/example');
  await page.screenshot({ path: '/tmp/plowshare-admin-project-ui.png' });
  await page.locator('#server-project-form button[type="submit"]').click();
  await expect(page.locator('#server-project-dialog')).toBeHidden();
  const result = await page.evaluate(async () => (await window.plowshare.request({ action: 'bootstrap' })).state);
  assert.equal(result.projects.find(row => row.name === 'Server example')?.workspace, '/srv/projects/example');
  assert.equal(fixture.frames.filter(row => row.type === 'project.create').length, 1);
  assert.equal(fixture.httpPaths.filter(path => path === '/v1/auth/setup').length, 1);
  for (const secret of ['fixture-temporary', 'fixture-password', 'fixture-access', 'fixture-refresh']) assert.ok(!JSON.stringify(result).includes(secret));
  await page.locator('#server-project-add').click();
  await page.locator('#server-project-type').selectOption('DISJOINT');
  await page.locator('#server-project-name').fill('Pipeline integration');
  await page.locator('#server-project-workspace').fill('/srv/pipeline/integration');
  await page.locator('#server-project-writes').fill('generated, reports');
  await page.locator('#server-project-form button[type="submit"]').click();
  await expect(page.locator('#server-project-dialog')).toBeHidden();
  assert.deepEqual(fixture.frames.filter(row => row.type === 'project.create').at(-1).payload, { name: 'Pipeline integration', workspace: '/srv/pipeline/integration', type: 'DISJOINT', writePaths: ['generated', 'reports'] });
  await page.locator('#server-admin-open').click();
  await expect(page.locator('#server-admin-dialog [data-account-name]')).toHaveText('fixture');
  await page.locator('#server-admin-dialog [data-role]').click();
  await expect(page.locator('#server-admin-dialog [data-error]')).toContainText('last enabled');
  await page.locator('#server-admin-dialog input[name="handle"]').fill('new-user');
  await page.locator('#server-admin-dialog [data-create] button').click();
  await expect(page.locator('#server-admin-dialog [data-account-name]')).toHaveText('new-user');
  await expect(page.locator('#server-admin-dialog [data-password]')).toHaveValue('fixture-one-time-password');
  await page.screenshot({path:'/tmp/plowshare-admin-accounts-ui.png'});
  const accountState=await page.evaluate(async()=>(await window.plowshare.request({action:'bootstrap'})).state);
  assert.ok(!JSON.stringify(accountState).includes('fixture-one-time-password'));
  assert.ok(!(await readFile(join(directory,'desktop-connection.json'),'utf8')).includes('fixture-one-time-password'));
  await page.locator('#server-admin-dialog [data-role]').click();
  await expect(page.locator('#server-admin-dialog [data-account-status]')).toContainText('Server administrator');
  await page.locator('#server-admin-dialog [data-enabled]').click();
  await expect(page.locator('#server-admin-dialog [data-account-status]')).toContainText('Disabled');
  await page.locator('#server-admin-dialog [data-enabled]').click();
  await expect(page.locator('#server-admin-dialog [data-account-status]')).toContainText('Enabled');
  await page.locator('#server-admin-dialog [data-reset]').click();
  await expect(page.locator('#server-admin-dialog [data-password]')).toHaveValue('fixture-reset-password');
  await page.locator('#server-admin-dialog [data-revoke]').click();
  await expect(page.locator('#server-admin-dialog [data-audit]')).toContainText('session.revoke');
  await expect(page.locator('#server-admin-dialog [data-credential]')).toBeHidden();
  await page.locator('#server-admin-dialog [data-services]').click();
  await page.locator('#service-admin-dialog input[name="handle"]').fill('ha-integration');
  await page.locator('#service-admin-dialog [data-create] button').click();
  await expect(page.locator('#service-admin-dialog [data-name]')).toHaveText('ha-integration');
  await page.locator('#service-admin-dialog [data-project]').selectOption('Server example');
  await page.locator('#service-admin-dialog [data-grant]').click();
  await expect(page.locator('#service-admin-dialog [data-scope-add]')).toBeEnabled();
  await page.locator('#service-admin-dialog [data-scope-add]').click();
  await page.locator('#service-admin-dialog input[name="name"]').fill('production');
  await page.locator('#service-admin-dialog [data-issue] button').click();
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('pss_fixture-service-1');
  await expect(page.locator('#service-admin-dialog [data-tokens]')).toContainText('Server example: contributor');
  const serviceState=await page.evaluate(async()=>(await window.plowshare.request({action:'bootstrap'})).state);
  assert.ok(!JSON.stringify(serviceState).includes('pss_fixture-service-1'));
  assert.ok(!(await readFile(join(directory,'desktop-connection.json'),'utf8')).includes('pss_fixture-service-1'));
  await page.locator('#service-admin-dialog [data-rotate]').click();
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('pss_fixture-service-2');
  await page.locator('#service-admin-dialog [data-revoke]').click();
  await expect(page.locator('#service-admin-dialog [data-tokens]')).toContainText('Revoked');
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('');
  await page.locator('#service-admin-dialog [data-enabled]').click();
  await expect(page.locator('#service-admin-dialog [data-status]')).toHaveText('Disabled');
  await page.locator('#service-admin-dialog [data-enabled]').click();
  await expect(page.locator('#service-admin-dialog [data-status]')).toHaveText('Enabled');
  await page.locator('#service-admin-dialog [data-rotate]').click();
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('pss_fixture-service-3');
  fixture.failServiceTokenMetadataOnce();
  await page.locator('#service-admin-dialog input[name="name"]').fill('metadata-refresh-test');
  await page.locator('#service-admin-dialog [data-issue] button').click();
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('pss_fixture-service-4');
  await expect(page.locator('#service-admin-dialog [data-error]')).toContainText('Token metadata unavailable');
  await page.screenshot({path:'/tmp/plowshare-service-accounts-ui.png'});
  await page.locator('#service-admin-dialog [data-close]').click();
  await expect(page.locator('#service-admin-dialog [data-secret]')).toHaveValue('');
  for(const type of ['admin.service.account.create','admin.service.token.revoke']) assert.equal(fixture.frames.filter(row=>row.type===type).length,1);
  assert.equal(fixture.frames.filter(row=>row.type==='admin.service.token.create').length,2);
  console.log('Service account smoke passed: create, grant project, scoped token issuance, rotation, revocation, disable/enable and transient credentials retained after metadata refresh failure.');
  await page.locator('#server-admin-dialog [data-close]').click();
  await expect(page.locator('#server-admin-dialog')).toBeHidden();
  await expect(page.locator('#server-admin-dialog [data-password]')).toHaveValue('');
  for(const type of ['admin.account.create','admin.account.reset','admin.session.revoke']) assert.equal(fixture.frames.filter(row=>row.type===type).length,1);
  await page.locator('[data-project-access="Server example"]').click();
  await expect(page.locator('#project-access-dialog [data-role]')).toContainText('manager');
  await page.locator('#project-access-dialog input[name="handle"]').fill('new-user');
  await page.locator('#project-access-dialog select[name="role"]').selectOption('VIEWER');
  await page.locator('#project-access-dialog [data-add] button').click();
  await expect(page.locator('#project-access-dialog [data-members]')).toContainText('new-user');
  await page.locator('#project-access-dialog select[aria-label="Role for new-user"]').selectOption('CONTRIBUTOR');
  await page.locator('#project-access-dialog [data-handle="new-user"]').click();
  await expect(page.locator('#project-access-dialog [data-changes]')).toContainText('contributor');
  await page.screenshot({path:'/tmp/plowshare-project-access-ui.png'});
  await page.locator('#project-access-dialog [data-remove="new-user"]').click();
  await expect(page.locator('#project-access-dialog [data-members]')).not.toContainText('new-user');
  await page.locator('#project-access-dialog [data-close]').click();
  console.log('Project access smoke passed: grant Viewer, change to Contributor, remove membership and inspect history.');
  console.log('Account administration smoke passed: creation, last-admin refusal, role changes, enable/disable, reset, revocation, audit and transient credentials.');
  console.log('Admin UI smoke passed: setup, saved account, role visibility, MANAGED and restricted DISJOINT creation, and no secrets in state.');
} finally {
  if (app) await app.close();
  await fixture.close();
  await rm(directory, { recursive: true, force: true });
}
