import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const profile = await mkdtemp(join(tmpdir(), 'plowshare-applications-'));
const fixture = await protocolFixture({ serverAdmin: false });
fixture.addServerProject({ name: 'Chatbot', kind: 'application', type: 'DISJOINT', role: 'VIEWER', readOnly: true, workspace: '/fixture/chatbot' });
fixture.addServerProject({ name: 'Managed app', kind: 'application', type: 'MANAGED', role: 'CONTRIBUTOR' });
fixture.addServerProject({ name: 'Remote files', kind: 'project', role: 'CONTRIBUTOR' });
fixture.setApplicationFile('Chatbot', 'notes.md', 'Viewer source');
fixture.setApplicationFile('Managed app', 'notes.md', 'Editable source', true);
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(profile, 'credentials'), PLOWSHARE_DESKTOP_PROFILE: profile, PLOWSHARE_DESKTOP_CONFIG: join(profile, 'config') };
delete env.ELECTRON_RUN_AS_NODE;
await mkdir('build/smoke', { recursive: true });
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const page = await app.firstWindow();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.evaluate(base => window.plowshare.request({ action: 'connect', base, handle: 'fixture', password: 'fixture-password' }), fixture.base);
  await expect(page.locator('#application-conversations [data-project="Chatbot"]')).toBeVisible();
  await expect(page.locator('#conversations [data-project="Remote files"]')).toBeVisible();
  await expect(page.locator('#conversations [data-project="Chatbot"]')).toHaveCount(0);
  await expect(page.locator('#application-conversations [data-project="Managed app"]')).toBeVisible();
  await expect(page.locator('#conversations [data-project="Managed app"]')).toHaveCount(0);
  await expect(page.locator('#application-conversations [data-project="Remote files"]')).toHaveCount(0);
  await expect(page.locator('#applications-toggle')).toContainText('Applications');
  await expect(page.locator('#projects-toggle')).toContainText('Projects');
  await expect(page.locator('#projects-toggle')).not.toContainText('Externals');
  await page.locator('[data-project="Chatbot"]').click();
  await expect(page.locator('#application-panel')).toBeVisible();
  await page.locator('#application-panel [data-files]').click();
  await page.locator('#application-panel [data-path]').fill('');
  await page.locator('#application-panel [data-browse]').click();
  await expect(page.locator('#application-panel')).toBeVisible();
  await page.locator('[data-application-path="notes.md"]').click();
  await expect(page.locator('#application-panel [data-text]')).toHaveValue('Viewer source');
  await expect(page.locator('#application-panel [data-text]')).toHaveAttribute('readonly', '');
  await expect(page.locator('#application-panel [data-save]')).toBeDisabled();
  await expect(page.locator('#send')).toBeDisabled();
  await expect(page.locator('#new-conversation')).toBeDisabled();
  await page.locator('#applications-toggle').click();
  await expect(page.locator('#sidebar-applications')).toBeHidden();
  await page.reload();
  await expect(page.locator('#applications-toggle')).toHaveAttribute('aria-expanded', 'false');
  await page.locator('#applications-toggle').click();
  await expect(page.locator('#sidebar-applications')).toBeVisible();
  await page.locator('#projects-toggle').click();
  await expect(page.locator('#sidebar-projects')).toBeHidden();
  await expect(page.locator('#application-conversations [data-project="Chatbot"]')).toBeVisible();
  await page.locator('#projects-toggle').click();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 700));
  const divider = page.locator('.pane-resizer[data-pane="sidebar"]');
  await divider.press('ArrowLeft');
  await divider.press('ArrowRight');
  for (const selector of ['#applications-toggle', '#projects-toggle', '#application-conversations [data-project="Chatbot"]', '#conversations [data-project="Remote files"]']) {
    await expect(page.locator(selector)).toBeVisible();
    const box = await page.locator(selector).boundingBox();
    const sidebar = await page.locator('#sidebar').boundingBox();
    assert.ok(box.x >= sidebar.x && box.x + box.width <= sidebar.x + sidebar.width + 1, `${selector} fits the resized sidebar`);
  }
  await page.locator('[data-project="Managed app"]').click();
  await page.locator('#application-panel [data-files]').click();
  await page.locator('[data-application-path="notes.md"]').click();
  const text = page.locator('#application-panel [data-text]');
  await expect(text).toHaveValue('Editable source');
  await text.fill('Draft saved on the server');
  await page.locator('#application-panel [data-save]').click();
  await expect(page.locator('#application-panel [data-save]')).toBeDisabled();
  assert.equal(fixture.frames.filter(frame => frame.type === 'application.file.save').length, 1);
  await text.fill('Keep my draft');
  fixture.setApplicationFile('Managed app', 'notes.md', 'Changed externally', true);
  await page.locator('#application-panel [data-save]').click();
  await expect(page.locator('#application-panel [data-error]')).toContainText('will not be replayed');
  await expect(text).toHaveValue('Keep my draft');
  await page.locator('#application-panel [data-read-current]').click();
  await expect(page.locator('#application-panel [data-use-current]')).toBeVisible();
  await expect(text).toHaveValue('Keep my draft');
  await page.locator('#application-panel [data-use-current]').click();
  await expect(text).toHaveValue('Changed externally');
  assert.equal(fixture.liveFileClaims.length, 0, 'Server source does not request a local file claim');
  const editorBox = await text.boundingBox(), panelBox = await page.locator('#application-panel').boundingBox();
  assert.ok(editorBox.x >= panelBox.x && editorBox.x + editorBox.width <= panelBox.x + panelBox.width + 1, 'Editor fits native resized Application pane');
  await page.screenshot({ path: 'build/smoke/applications-narrow.png' });
  fixture.setRefuseProjects(true);
  await page.locator('#refresh').click();
  await expect(page.locator('#application-conversations [role="alert"]')).toContainText('listing unavailable');
  fixture.setRefuseProjects(false);
  await page.locator('#refresh').click();
  await expect(page.locator('#application-conversations [data-project="Chatbot"]')).toBeVisible();
  for (const [selector, operation] of [['data-runtime', 'orchestration.definitions'], ['data-memory', 'memory.index'], ['data-board', 'board.topics']]) {
    await page.locator('[data-project="Managed app"]').click();
    await page.locator(`#application-panel [${selector}]`).click();
    await expect.poll(() => fixture.frames.some(frame => frame.type === operation && frame.payload.project === 'Managed app')).toBe(true);
  }
  await page.locator('[data-project="Managed app"]').click();
  fixture.removeServerProject('Managed app');
  await page.locator('#refresh').click();
  await expect(page.locator('#application-panel')).toBeHidden();
  await expect(page.locator('#application-conversations [data-project="Managed app"]')).toHaveCount(0);
  assert.deepEqual(errors, []);
  console.log('Application workspace smoke passed: separate groups, read-only and writable server files, stale revisions and retained drafts, scoped view shortcuts, revoked access, no local file claims and native window/sidebar resize.');
} finally {
  await app?.close();
  await fixture.close();
  await rm(profile, { recursive: true, force: true });
}
