import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';
const temporary = await realpath(await mkdtemp(join(tmpdir(), 'plowshare-builder-'))), root = join(temporary, 'Research');
await mkdir(root);
let granted = true;
const fixture = await protocolFixture({ authoring: true, agentRoster: () => [{ name: 'fixture-bot', bot: false, served: true, preferred: true, orchestrations: granted ? ['design_orchestration'] : [] }] });
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(temporary, 'credentials'), PLOWSHARE_DESKTOP_CONFIG: join(temporary, 'config'), PLOWSHARE_DESKTOP_PROFILE: join(temporary, 'profile') }; delete env.ELECTRON_RUN_AS_NODE;
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const main = await app.firstWindow(), errors = []; main.on('pageerror', error => errors.push(error.message));
  await main.evaluate(base => window.plowshare.request({ action: 'connect', base, handle: 'fixture', password: 'fixture-password' }), fixture.base);
  const opened = app.waitForEvent('window'); await main.evaluate(() => window.plowshare.request({ action: 'activity', view: 'builder' }));
  const builder = await opened; builder.on('pageerror', error => errors.push(error.message));
  await expect(builder.locator('#activity-title')).toHaveText('Orchestration builder');
  await builder.locator('#builder-project').selectOption('Empty workspace'); await builder.locator('#builder-prepare').click();
  await expect(builder.locator('#builder-ready')).toContainText('folder'); await expect(builder.locator('#builder-start')).toBeDisabled();
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, 0);
  await app.evaluate(({ dialog }, root) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [root] }); }, root);
  await main.evaluate(() => window.plowshare.request({ action: 'files-choose' }));
  await builder.locator('#builder-project').selectOption('Research'); await builder.locator('#builder-prepare').click();
  await expect(builder.locator('#builder-ready')).toContainText('Ready.');
  granted = false; await builder.locator('#builder-prepare').click(); await expect(builder.locator('#builder-ready')).toContainText('granted');
  await assert.rejects(builder.evaluate(() => window.plowshare.request({ action: 'builder-start', project: 'Research', agent: 'fixture-bot', intent: 'Read sources and produce a report.' })), /granted/);
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, 0);
  granted = true; await builder.locator('#builder-prepare').click(); await expect(builder.locator('#builder-start')).toBeEnabled();
  await builder.locator('#builder-revision').selectOption('deep_research');
  await builder.locator('#builder-intent').fill('Revise the source review procedure to ask me before publication.');
  await builder.locator('#builder-start').click(); await expect(builder.locator('.builder-review')).toContainText('draft_procedure');
  await expect(builder.locator('.builder-review pre').first()).toContainText('tools: [file_read]');
  await expect(builder.locator('.builder-review')).toContainText('sha256:' + 'a'.repeat(64));
  await expect(builder.locator('.builder-review')).toContainText('VALID — loader trial passed.');
  await expect(builder.locator('.run-question')).toContainText('Grants file_read beyond fixture-bot');
  await mkdir('build/smoke', { recursive: true }); await builder.screenshot({ path: 'build/smoke/builder-review.png' });
  await builder.setViewportSize({ width: 860, height: 620 }); await builder.screenshot({ path: 'build/smoke/builder-review-compact.png' }); await builder.setViewportSize({ width: 1160, height: 800 });
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, 1);
  assert.match(fixture.frames.find(row => row.type === 'agent.run').payload.task, /revising deep_research/);
  await assert.rejects(builder.evaluate(() => window.plowshare.request({ action: 'builder-start', project: 'Research', agent: 'fixture-bot', intent: 'Duplicate launch' })), /still active/);
  await builder.locator('[data-question-defer]').click(); await builder.locator('#activity-refresh').click();
  await expect(builder.locator('.run-question')).toContainText('Deferred'); await expect(builder.locator('#builder-intent')).toHaveValue('Revise the source review procedure to ask me before publication.');
  assert.equal(fixture.frames.some(row => row.type === 'orchestration.answer'), false);
  await builder.locator('[data-question-resume]').click();
  await builder.locator('[data-choice="0"] input[value="Install"]').check();
  fixture.replaceQuestion(); await builder.locator('#run-answer-send').click(); await expect(builder.locator('#activity-error')).toContainText('changed');
  assert.equal(fixture.frames.some(row => row.type === 'orchestration.answer'), false);
  await builder.locator('[data-choice="0"] input[value="Don’t install"]').check(); await builder.locator('#run-answer-send').click(); await expect(builder.locator('.run-notice')).toContainText('Answer recorded');
  assert.equal(fixture.frames.filter(row => row.type === 'orchestration.answer').length, 1);
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, 1);
  await assert.rejects(main.evaluate(() => window.plowshare.request({ action: 'builder-start', project: 'Research', agent: 'fixture-bot', intent: 'outside the authoring window' })), /Open Activity/);
  await expect(builder.locator('#builder-start')).toBeEnabled();
  if (!(await builder.locator('#builder-form').evaluate(el => el.open))) await builder.locator('#builder-form summary').click();
  fixture.loseAuthoringReply(); await builder.locator('#builder-start').click(); await expect(builder.locator('#builder-launch')).toContainText('unknown');
  const launches = fixture.frames.filter(row => row.type === 'agent.run').length;
  if (!(await builder.locator('#builder-form').evaluate(el => el.open))) await builder.locator('#builder-form summary').click();
  await builder.locator('#builder-prepare').click(); await builder.locator('#activity-refresh').click();
  await assert.rejects(builder.evaluate(() => window.plowshare.request({ action: 'builder-start', project: 'Research', agent: 'fixture-bot', intent: 'Do not replay' })), /uncertain|still active/);
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, launches);
  await expect(builder.locator('#run-answer-send')).toBeEnabled();
  await builder.locator('[data-choice="0"] input[value="Install"]').check(); await builder.locator('#run-answer-send').click(); await expect(builder.locator('.run-notice')).toContainText('Answer recorded');
  assert.equal(fixture.frames.filter(row => row.type === 'orchestration.answer').length, 2);
  assert.deepEqual(fixture.frames.filter(row => row.type === 'orchestration.answer').at(-1).payload.choices, [{ header: 'Install', chosen: ['Install'] }]);
  assert.equal(fixture.frames.filter(row => row.type === 'agent.run').length, launches);
  await mkdir('build/smoke', { recursive: true }); await builder.screenshot({ path: 'build/smoke/builder.png' });
  await builder.setViewportSize({ width: 860, height: 620 }); await builder.screenshot({ path: 'build/smoke/builder-compact.png' });
  assert.deepEqual(errors, []); console.log('PASS: native builder project/grant preflight, revision intent, one correlated WS launch, exact draft and grants, deferred review, stale installation guard, explicit decline/install, lost-reply reconnect without replay and scoped IPC.');
} finally { if (app) await app.close(); await fixture.close(); await rm(temporary, { recursive: true, force: true }); }
