import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const profile = await mkdtemp(join(tmpdir(), 'plowshare-commands-'));
const entry = { command: '/skill:review', aliases: [], kind: 'skill', name: 'review', description: 'Review <this> change', argumentHint: 'Change to review', executor: 'interlocutor', mode: null, tier: 'PROJECT', hash: 'fixture-hash', agentVisible: false };
const fixture = await protocolFixture({ agentRoster: async () => [{ name: 'fixture-bot', bot: true, served: true, preferred: true, model: 'fixture-model', description: 'Bot', tools: [], commands: [entry, { ...entry, command: '/orchestration:research', name: 'research', kind: 'orchestration', description: 'Research the topic', executor: 'researcher' }] }] });
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(profile, 'credentials'), PLOWSHARE_DESKTOP_CONFIG: join(profile, 'config'), PLOWSHARE_DESKTOP_PROFILE: profile }; delete env.ELECTRON_RUN_AS_NODE;
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const main = await app.firstWindow(), errors = [];
  main.on('pageerror', error => errors.push(error.message));
  await main.evaluate(base => window.plowshare.request({ action: 'connect', base, handle: 'fixture', password: 'fixture-password' }), fixture.base);
  const commands = main.locator('#agent-commands');
  await main.locator('#info-commands-tab').click();
  await expect(main.locator('#sidebar #agent-commands')).toHaveCount(0);
  await expect(main.locator('#inspector [role=tab]')).toHaveCount(3);
  await expect(commands).toContainText('2 available');
  await expect(commands).toContainText('Review <this> change');
  await expect(commands.locator('h3')).toContainText(['Skills', 'Orchestrations', 'Workspace commands']);
  const picker = main.locator('#slash-commands');
  await main.locator('#draft').fill('/');
  await expect(picker).toBeVisible();
  await expect(picker).toContainText('/help');
  await expect(picker).toContainText('/skill:review');
  await expect(picker).toContainText('/orchestration:research');
  await main.locator('#draft').press('ArrowDown');
  await expect(picker.locator('[aria-selected=true]')).toContainText('/commands');
  await main.locator('#draft').press('ArrowUp');
  await expect(picker.locator('[aria-selected=true]')).toContainText('/help');
  await main.locator('#draft').fill('/orchestration:r');
  await main.locator('#draft').press('Enter');
  await expect(main.locator('#draft')).toHaveValue('/orchestration:research ');
  await expect(picker).toBeHidden();
  await main.locator('#draft').fill('/skill:r');
  await main.locator('#draft').press('Tab');
  await expect(commands.locator('select')).toBeFocused();
  await expect(main.locator('#draft')).toHaveValue('/skill:review ');
  await main.locator('#draft').fill('/');
  await main.locator('#draft').press('Escape');
  await expect(picker).toBeHidden();
  await main.locator('#draft').press('Enter');
  await expect(main.locator('#draft')).toHaveValue('');
  await main.locator('#draft').fill('/help');
  await main.locator('#send').click();
  await expect(main.locator('#draft')).toHaveValue('');
  await expect(main.locator('#info-commands-tab')).toHaveAttribute('aria-selected', 'true');
  await main.locator('#draft').fill('/unknown');
  await main.locator('#draft').press('Enter');
  await expect(main.locator('#error')).toContainText('Unknown command: /unknown');
  await expect(main.locator('#draft')).toHaveValue('/unknown');
  await main.locator('#dismiss-error').click();
  await main.locator('#draft').fill('Review\nthis exact change');
  await commands.locator('[data-command-index="0"]').click();
  await expect(commands).toContainText('Choose how the skill receives context.');
  await expect(main.locator('#draft')).toHaveValue('Review\nthis exact change');
  await commands.locator('select').selectOption('SUMMARISED');
  await commands.locator('[data-command-index="0"]').click();
  await expect(main.locator('#draft')).toHaveValue('/skill:review --mode=SUMMARISED Review\nthis exact change');
  assert.equal(fixture.frames.some(frame => frame.type === 'agent.run' || frame.type === 'orchestration.start'), false);
  await main.setViewportSize({ width: 1120, height: 780 });
  await expect(main.locator('#info-commands-tab')).toBeInViewport();
  await expect(commands.locator('[data-command-index="0"]')).toBeInViewport();
  await mkdir('build/smoke', { recursive: true }); await main.screenshot({ path: 'build/smoke/commands.png' });
  await main.locator('#draft').fill('Research the original topic');
  await commands.locator('[data-command-index="1"]:not([data-command-start])').click();
  await expect(main.locator('#draft')).toHaveValue('/orchestration:research Research the original topic');
  fixture.setWorkflowAckMissing(true);
  await commands.locator('[data-command-start]').click();
  await expect(commands.locator('[role="alert"]:visible')).toContainText('request ID is retained');
  assert.equal(fixture.workflowRunCount(),1);
  const key=fixture.frames.find(frame=>frame.type==='orchestration.start').payload.requestId;
  await main.reload();
  await main.locator('#info-commands-tab').click();
  await expect(main.locator('#draft')).toHaveValue('/orchestration:research Research the original topic');
  fixture.setWorkflowAckMissing(false);
  await commands.locator('[data-command-start]').click();
  await expect(commands.locator('[role="status"]')).toContainText('Workflow started');
  const starts=fixture.frames.filter(frame=>frame.type==='orchestration.start');
  assert.deepEqual(starts.map(frame=>frame.payload.requestId),[key,key]);
  assert.equal(starts[0].payload.definition,'research');
  assert.equal(starts[0].payload.agent,'fixture-bot');
  assert.equal(starts[0].payload.request,'Research the original topic');
  assert.equal(fixture.workflowRunCount(),1,'Recovering a missing acknowledgment never starts another run');
  assert.equal(fixture.frames.some(frame=>frame.type==='agent.run'),false,'Direct workflow launch bypasses caller-model dispatch');
  const invocation = ' /skill:review --mode=SUMMARISED Review\nthis exact change ';
  await main.locator('#draft').fill(invocation);
  await main.locator('#send').click();
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'agent.run').length).toBe(1);
  assert.equal(fixture.frames.find(frame => frame.type === 'agent.run').payload.task, invocation);
  assert.deepEqual(errors, []);
  console.log('PASS: human-visible skills hidden from the model, slash completion and native help without model calls, scoped server catalog, explicit context selection, and durable workflow recovery without duplicate runs.');
} finally { if (app) await app.close(); await fixture.close(); await rm(profile, { recursive: true, force: true }); }
