import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, writeFile, readFile, realpath, symlink, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const temporary = await realpath(await mkdtemp(join(tmpdir(), 'plowshare-desktop-files-')));
const root = join(temporary, 'Research');
await mkdir(root); await writeFile(join(root, 'notes.md'), 'Original notes\n');
await writeFile(join(temporary, 'outside.txt'), 'private');
await symlink(join(temporary, 'outside.txt'), join(root, 'escape.txt'));
await mkdir('build/smoke', { recursive: true });
const fixture = await protocolFixture();
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(temporary, 'credentials'), PLOWSHARE_DESKTOP_CONFIG: join(temporary, 'config'), PLOWSHARE_DESKTOP_PROFILE: join(temporary, 'profile') };
delete env.ELECTRON_RUN_AS_NODE;
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const page = await app.firstWindow();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const bootstrap = () => page.evaluate(() => window.plowshare.request({ action: 'bootstrap' }));
  await expect(page.locator('#files-label')).toHaveText('Connect files');
  await expect(page.locator('#file-access-prompt')).toBeHidden();
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'files-choose' })), /Connect to the server/);
  await page.evaluate(({ base }) => window.plowshare.request({ action: 'connect', base, handle: 'fixture', password: 'fixture-password' }), { base: fixture.base });
  assert.equal(fixture.fileClaim, undefined, 'Connecting never roots the process cwd');
  await expect(page.locator('#file-access-prompt')).toBeVisible();
  await expect(page.locator('#file-access-description')).toContainText('read and change files');
  await expect(page.locator('#file-access-allow')).toHaveText('Approve');
  await page.locator('#file-access-deny').click();
  await expect(page.locator('#file-access-prompt')).toBeHidden();
  await expect(page.locator('#files-label')).toHaveText('File access denied');
  assert.equal(fixture.fileClaim, undefined, 'Denying file access grants nothing');
  await page.locator('#files-open').click(); await page.locator('#inspector-close').click();
  await app.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }); });
  await page.locator('#file-access-allow').click();
  assert.equal(fixture.fileClaim, undefined, 'Canceling the access picker grants nothing');
  await expect(page.locator('#file-access-prompt')).toBeVisible();
  await app.evaluate(({ dialog }, root) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [root] }); }, root);
  await page.locator('#file-access-allow').click();
  await expect(page.locator('#info-files')).toBeHidden();
  await expect(page.locator('[data-project="Research"]')).toHaveAttribute('aria-current', 'true');
  await expect(page.locator('#files-label')).toHaveText('Files connected');
  await expect(page.locator('#file-access-prompt')).toBeHidden();
  assert.equal(fixture.fileClaim.root, root);
  assert.equal(await readFile(join(root, '.plowshare/project'), 'utf8'), 'Research\n');
  assert.equal(fixture.fileClaim.session, fixture.eventSession);
  assert.deepEqual((await fixture.file({ op: 'roots' })).paths, [root]);
  assert.deepEqual((await fixture.file({ op: 'read', path: 'notes.md' })).span.lines, ['Original notes']);
  assert.equal((await fixture.file({ op: 'write', path: 'new.md', content: 'New file\n' })).result.kind, 'written');
  assert.equal((await fixture.file({ op: 'edit', path: 'notes.md', replacing: 'Original', content: 'Updated' })).result.kind, 'edited');
  assert.equal(await readFile(join(root, 'notes.md'), 'utf8'), 'Updated notes\n');
  assert.equal((await fixture.file({ op: 'move', path: 'new.md', to: 'moved.md' })).result.kind, 'moved');
  assert.equal((await fixture.file({ op: 'delete', path: 'moved.md' })).result.kind, 'deleted');
  assert.ok((await fixture.file({ op: 'glob', pattern: '**/*.md' })).paths.includes(join(root, 'notes.md')));
  assert.equal((await fixture.file({ op: 'grep', pattern: '**/*.md', needle: 'Updated' })).found.matches.length, 1);
  for (const path of ['../outside.txt', 'escape.txt', '.plowshare/project']) assert.equal((await fixture.file({ op: 'read', path })).outcome, 'refused');
  assert.deepEqual((await fixture.file({ op: 'read', path: '.plowshare/environment.yml', purpose: 'definitions' })).span.lines, ['local:', '  mode: ask']);
  assert.equal((await fixture.file({ op: 'run', path: root, argv: ['/usr/bin/printf', 'local command'], timeoutMillis: 1000 })).stdout, 'local command');
  // A trajectory window must not select or withdraw a local filesystem.
  await page.locator('#new-conversation').click();
  const newWindow = app.waitForEvent('window'); await page.locator('#trajectory-open').click();
  const trajectory = await newWindow;
  await assert.rejects(trajectory.evaluate(() => window.plowshare.request({ action: 'files-withdraw' })), /only read their own conversation/);
  await trajectory.close();
  await page.locator('#files-open').click();
  await expect(page.locator('#files-root')).toHaveText(`${fixture.fileClaim.machine} · ${root}`);
  await page.screenshot({ path: 'build/smoke/files-connected.png' });
  await page.locator('#inspector-close').click();
  fixture.loseFiles();
  await expect(page.locator('#files-label')).toHaveText('Files disconnected');
  assert.equal((await bootstrap()).state.files.status, 'lost');
  await expect(page.locator('#file-access-title')).toHaveText('Restore file access');
  await expect(page.locator('#file-access-description')).toContainText(root);
  await page.locator('#draft').fill('Keep my draft while allowing access');
  const runCalls = fixture.frames.filter(frame => frame.type === 'agent.run').length;
  await page.setViewportSize({ width: 760, height: 600 });
  await page.locator('#file-access-allow').scrollIntoViewIfNeeded();
  const composerBox = await page.locator('#composer').boundingBox();
  assert.ok(composerBox && composerBox.y + composerBox.height <= 600, 'Stacked approval prompts leave the composer inside the compact window');
  await page.screenshot({ path: 'build/smoke/file-access-prompt.png' });
  await page.locator('#file-access-allow').click();
  await expect(page.locator('#files-label')).toHaveText('Files connected');
  await expect(page.locator('#file-access-prompt')).toBeHidden();
  await expect(page.locator('#draft')).toHaveValue('Keep my draft while allowing access');
  assert.equal(fixture.frames.filter(frame => frame.type === 'agent.run').length, runCalls, 'Allowing files never replays an agent turn');
  await page.locator('#files-open').click(); await page.locator('#files-withdraw').click();
  await expect(page.locator('#files-label')).toHaveText('Connect files');
  await expect.poll(() => fixture.fileClaim).toBeUndefined();
  await page.locator('#inspector-close').click();
  await page.locator('#file-access-deny').click();
  await expect(page.locator('#file-access-prompt')).toBeHidden();
  const denied = (await bootstrap()).state.projectFolders.find(row => row.name === 'Research');
  assert.equal(denied.enabled, false, 'Denying remembered access keeps automatic restoration disabled');
  await page.locator('#files-open').click();
  // Refusal is explicit and never creates a marker in a previously unmarked root.
  const other = join(temporary, 'refused'); await mkdir(other);
  await app.evaluate(({ dialog }, root) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [root] }); }, other);
  fixture.setRefuseFiles(true);
  await page.locator('#files-choose').click(); await expect(page.locator('#files-error')).toContainText('already rooted');
  await assert.rejects(readFile(join(other, '.plowshare/project')), { code: 'ENOENT' });
  fixture.setRefuseFiles(false); await page.locator('#inspector-close').click();
  // Disconnect withdraws a live claim; reconnect never replays it.
  await app.evaluate(({ dialog }, root) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [root] }); }, root);
  await page.evaluate(() => window.plowshare.request({ action: 'files-choose', project: 'Research' }));
  assert.ok(fixture.fileClaim);
  await page.evaluate(() => window.plowshare.request({ action: 'disconnect' }));
  await page.evaluate(({ base }) => window.plowshare.request({ action: 'connect', base, handle: 'fixture', password: 'fixture-password' }), { base: fixture.base });
  assert.equal((await bootstrap()).state.files.status, 'ready');
  assert.equal(fixture.fileClaim.project, 'Research', 'Remembered enabled projects restore after login');
  // Quit must withdraw an active claim too.
  await page.evaluate(() => window.plowshare.request({ action: 'files-choose' }));
  assert.ok(fixture.fileClaim);
  await app.close(); app = undefined;
  await expect.poll(() => fixture.fileClaim).toBeUndefined();
  assert.deepEqual(errors, []);
  console.log('Native files smoke passed: presence, real file operations, command execution, fences, scope, withdrawal, refusal, claim loss and reconnect.');
} finally {
  await app?.close(); await fixture.close(); await rm(temporary, { recursive: true, force: true });
}
