import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const profile=await mkdtemp(join(tmpdir(),'plowshare-information-smoke-')),fixture=await protocolFixture();
const env={...process.env,PLOWSHARE_CONFIG_DIR:join(profile,'credentials'),PLOWSHARE_DESKTOP_CONFIG:join(profile,'config'),PLOWSHARE_DESKTOP_PROFILE:profile};delete env.ELECTRON_RUN_AS_NODE;
const count=type=>fixture.frames.filter(frame=>frame.type===type).length;
let app;
try {
  fixture.setInformationExtraction('failed');
  app=await electron.launch({executablePath,args:[resolve('.')],env});
  const main=await app.firstWindow(),errors=[];main.on('pageerror',error=>errors.push(error.message));
  await main.locator('#connection-button').click();await main.locator('#server-url').fill(fixture.base);await main.locator('#handle').fill('fixture');await main.locator('#password').fill('fixture-password');await main.locator('#submit-connection').click();await expect(main.locator('#connection-label')).toHaveText('Connected');
  await main.locator('#library-open').click();
  // Library is an embedded WebContentsView; observe the loaded page rather than a native-window event.
  await expect.poll(()=>app.windows().some(page=>page.url()==='plowshare://app/library.html'),{timeout:30000}).toBe(true);
  const library=app.windows().find(page=>page.url()==='plowshare://app/library.html');library.on('pageerror',error=>errors.push(error.message));
  await library.locator('#library-documents').click();await library.locator('#document-sources > summary').click();
  const sources=library.locator('#document-source-panel');await sources.locator('.information-row').click();
  await expect(sources.locator('[data-source]')).toContainText('No readable text was extracted');
  await expect(sources.locator('[data-source]')).toContainText('paste readable text');
  await expect(sources.locator('[data-ask] button')).toBeDisabled();
  await expect(sources.locator('.information-processing')).not.toContainText('settings changed');
  // A programmatic submit must also be blocked before any paid work is submitted.
  await sources.locator('[data-ask] input').fill('Read this failed source');await sources.locator('[data-ask]').dispatchEvent('submit');
  assert.equal(count('information.ask'),0);assert.equal(count('information.read'),0);
  await library.evaluate(()=>document.activeElement?.blur());
  const statuses=count('information.status');await expect.poll(()=>count('information.status'),{timeout:8000}).toBeGreaterThan(statuses);
  assert.equal(count('information.read'),0,'Polling a failed extraction never reads absent text.');
  await sources.locator('[data-repair-source]').click();await expect(sources.locator('[data-revise] textarea')).toBeFocused();await expect(sources.locator('[data-manage-source]')).toHaveAttribute('open','');
  await mkdir('build/smoke',{recursive:true});await library.screenshot({path:'build/smoke/information-extraction-failed.png'});
  fixture.setInformationExtraction('pending');await sources.locator('[data-refresh]').click();await expect(sources.locator('[data-source]')).toContainText('Preparing source text');assert.equal(count('information.read'),0);
  fixture.setInformationExtraction('ready');await sources.locator('[data-refresh]').click();await expect(sources.locator('[data-passage]')).toContainText('A retained claim.');await expect(sources.locator('[data-ask] button')).toBeEnabled();
  fixture.setInformationReadError('this revision has not been extracted');await sources.locator('[data-refresh]').click();await expect(sources.locator('[data-source]')).toContainText('no saved extraction');await expect(sources.locator('[data-source]')).not.toContainText('Error invoking remote method');
  const reads=count('information.read'),afterFailure=count('information.status');await library.evaluate(()=>document.activeElement?.blur());await expect.poll(()=>count('information.status'),{timeout:8000}).toBeGreaterThan(afterFailure);
  assert.equal(count('information.read'),reads,'Unchanged status does not replay a refused read.');
  fixture.setInformationReadError('');await sources.locator('[data-refresh]').click();await expect(sources.locator('[data-passage]')).toContainText('A retained claim.');assert.equal(count('information.read'),reads+1,'Explicit refresh can recover after a read failure.');
  assert.equal(count('information.retry'),0);assert.equal(count('information.ask'),0);assert.deepEqual(errors,[]);
  await sources.locator('[data-faceting] > summary').click();
  await expect(sources.locator('[data-facet-total]')).toHaveText('· 1 version');
  await sources.locator('.information-tag-relations > summary').click();
  await expect(sources.locator('[data-tag-graph]')).toContainText('postgresql (1)');
  await sources.locator('[data-tag-graph]').scrollIntoViewIfNeeded();
  await library.screenshot({path:'build/smoke/information-tag-groups.png'});
  await sources.locator('[data-group-browse="databases"]').click();
  await expect(sources.locator('[data-facet-remove="tagGroup"]')).toContainText('databases');
  await sources.locator('[data-facet="autoTag"]').selectOption('postgresql');
  await expect(sources.locator('[data-facet-remove="autoTag"]')).toContainText('postgresql');
  await sources.locator('[data-facet="tags"]').selectOption('my project');
  await expect(sources.locator('[data-facet-remove="tags"]')).toContainText('my project');
  await sources.locator('[data-facet="documentAuthor"]').selectOption('Ada Lovelace');
  await expect(sources.locator('[data-facet-remove="documentAuthor"]')).toContainText('Ada Lovelace');
  const filtered=fixture.frames.filter(frame=>frame.type==='information.list').at(-1).payload.filter;
  assert.deepEqual(filtered,{tagGroup:'databases',autoTag:['postgresql'],tags:['my project'],documentAuthor:'Ada Lovelace'});
  await sources.locator('.information-row').click();
  await expect(sources.locator('.information-document-author')).toHaveText('Document author: Ada Lovelace');
  await expect(sources.locator('.information-tags')).toContainText('Automatic tags: postgresql');
  await sources.locator('.information-tag-metadata > summary').click();
  await sources.locator('[data-tags] input').fill('my project, reviewed');await sources.locator('[data-tags] button').click();
  await expect(sources.locator('.information-tags')).toContainText('Your tags: my project, reviewed');
  const updated=fixture.frames.filter(frame=>frame.type==='information.tags').at(-1).payload;
  assert.deepEqual(updated.tags,['my project','reviewed']);assert.equal('autoTag' in updated,false);assert.ok(updated.requestId);
  await sources.locator('[data-facet-clear]').click();
  await sources.locator('.information-row').click();
  if (await sources.locator('.information-tag-metadata').getAttribute('open') === null) await sources.locator('.information-tag-metadata > summary').click();
  await sources.locator('.information-tag-groups > summary').click();
  await sources.locator('[data-tag-groups] textarea').fill('my work: postgresql, reviewed');
  await sources.locator('[data-tag-groups] button').first().click();
  await expect(sources.locator('.information-tag-groups > summary')).toContainText('your override');
  const groupUpdate=fixture.frames.filter(frame=>frame.type==='information.tags.groups').at(-1).payload;
  assert.deepEqual(groupUpdate.groups,{'my work':['postgresql','reviewed']});assert.equal('tags' in groupUpdate,false);assert.equal('autoTag' in groupUpdate,false);assert.ok(groupUpdate.requestId);
  await expect(sources.locator('.information-tag-groups')).toHaveAttribute('open','');
  await sources.locator('[data-use-auto-groups]').click();
  await expect(sources.locator('.information-tag-groups > summary')).toContainText('automatic');
  assert.equal(fixture.frames.filter(frame=>frame.type==='information.tags.groups').at(-1).payload.groups,null);
  await expect(sources.locator('[data-tag-groups] textarea')).toHaveValue('databases: postgresql');
  await expect(sources.locator('[data-facet-remove]')).toHaveCount(0);
  await sources.locator('[data-facet-search] input').fill('nothing matches');await sources.locator('[data-facet-search] button').first().click();
  await expect(sources.locator('[data-facet-total]')).toHaveText('· 0 versions');await expect(sources.locator('.information-row')).toHaveCount(0);
  await sources.locator('[data-facet-remove="search"]').click();await expect(sources.locator('.information-row')).toHaveCount(1);
  assert.deepEqual(errors,[]);
  await library.screenshot({path:'build/smoke/information-facets.png'});
  console.log('PASS: failed/pending extraction states, no absent-text reads or paid submissions, accurate pending labels, replacement-text recovery, readable recovery no polling loop after a refused read, intersected facet filters/counts, document-author display/filtering, distinct user/automatic tags, category graph browsing, owner group overrides and returning to automatic grouping.');
} finally {if(app)await app.close();await fixture.close();await rm(profile,{recursive:true,force:true});}
