import { connectionDirectory } from '../../sdk/node/build/connections.js';
import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, readFile, readdir, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const directory = await mkdtemp(join(tmpdir(), 'plowshare-desktop-login-'));
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: directory, PLOWSHARE_DESKTOP_PROFILE: join(directory, 'profile') };
delete env.ELECTRON_RUN_AS_NODE; delete env.PLOWSHARE_DESKTOP_CONFIG;
const fixture = await protocolFixture({ rotateTokens: true });
const preference = join(directory, 'config.json');
let app;
const launch = async () => {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const page = await app.firstWindow();
  await page.locator('#connection-button').waitFor();
  await page.evaluate(() => window.plowshare.request({ action: 'bootstrap' }));
  return page;
};
const state = page => page.evaluate(async () => (await window.plowshare.request({ action: 'bootstrap' })).state);
const close = async () => { await app.close(); app = undefined; };
try {
  let page = await launch();
  await page.locator('#connect-sidebar').click();
  await page.locator('#server-url').fill(fixture.base);
  await page.locator('#handle').fill('fixture');
  await page.locator('#password').fill('fixture-password');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-dialog')).toBeHidden();
  assert.equal((await state(page)).connected, true);
  const config = JSON.parse(await readFile(preference, 'utf8'));
  assert.equal(config.version, 1); assert.equal(config.connections.length, 1);
  assert.equal(config.connections[0].server, fixture.base); assert.equal(config.connections[0].account, 'fixture'); assert.equal(config.connections[0].reconnect, true);
  assert.equal((await stat(preference)).mode & 0o777, 0o600);
  const privateDirectory = join(connectionDirectory(fixture.base, 'fixture', directory), 'credentials');
  const files = await readdir(privateDirectory);
  assert.equal(files.length, 1);
  const saved = JSON.parse(await readFile(join(privateDirectory, files[0]), 'utf8'));
  assert.equal(saved.origin, fixture.base); assert.equal(saved.handle, 'fixture');
  assert.ok(saved.tokens.access && saved.tokens.refresh);
  assert.ok(!(await readFile(preference, 'utf8')).includes('fixture-password'));
  await close();
  page = await launch();
  assert.equal((await state(page)).connected, true);
  assert.equal((await state(page)).base, fixture.base);
  assert.equal((await state(page)).handle, 'fixture');
  assert.equal(fixture.loginCount(), 1, 'Fresh process must use saved tokens with no form submission.');
  await assert.rejects(page.evaluate(base => window.plowshare.request({ action: 'connect', base, handle: 'another-account', password: '' }), fixture.base), /Sign in first/);
  assert.equal((await state(page)).handle, 'another-account');
  assert.equal((await state(page)).connected, false);
  await page.evaluate(name => window.plowshare.request({ action: 'connection-select', name }), config.connections[0].name);
  await page.locator('#connect-sidebar').click();
  await expect(page.locator('#server-url')).toHaveValue(fixture.base);
  await expect(page.locator('#handle')).toHaveValue('fixture');
  await expect(page.locator('#password')).toHaveValue('');
  const serialized = JSON.stringify(await state(page));
  assert.ok(!serialized.includes('fixture-access') && !serialized.includes('fixture-refresh') && !serialized.includes('fixture-password'));
  await close();
  // Existing CLI/GUI credentials work even before a desktop preference exists.
  await rm(preference);
  page = await launch();
  assert.equal((await state(page)).connected, true);
  assert.equal(fixture.loginCount(), 1);
  await page.evaluate(() => window.plowshare.request({ action: 'disconnect' }));
  await close();
  page = await launch();
  assert.equal((await state(page)).connected, false, 'Explicit disconnect must survive restart.');
  await page.locator('#connect-sidebar').click();
  await expect(page.locator('#server-url')).toHaveValue(fixture.base);
  await expect(page.locator('#password')).toHaveValue('');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-dialog')).toBeHidden();
  assert.equal(fixture.loginCount(), 1);
  await close();
  await rm(privateDirectory, { recursive: true });
  page = await launch();
  assert.equal((await state(page)).connected, false);
  assert.match((await state(page)).connectionPersistenceError, /Saved connection could not be restored/);
  await page.locator('#connect-sidebar').click();
  await expect(page.locator('#server-url')).toHaveValue(fixture.base);
  await expect(page.locator('#handle')).toHaveValue('fixture');
  await page.locator('#password').fill('fixture-password');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-dialog')).toBeHidden();
  assert.equal((await state(page)).connected, true);
  assert.equal((await state(page)).connectionPersistenceError, undefined);
  assert.equal(fixture.loginCount(), 2);
  console.log('Desktop login smoke passed: private token persistence, remembered server/account, automatic fresh-process reuse, existing shared login discovery, explicit disconnect, missing credentials and manual recovery.');
} finally {
  if (app) await app.close();
  await fixture.close();
  await rm(directory, { recursive: true, force: true });
}
