import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';
const directory=await mkdtemp(join(tmpdir(),'plowshare-recovery-'));
const fixture=await protocolFixture({rotateTokens:true});
const env={...process.env,PLOWSHARE_CONFIG_DIR:directory,PLOWSHARE_DESKTOP_PROFILE:join(directory,'profile')};delete env.ELECTRON_RUN_AS_NODE;delete env.PLOWSHARE_DESKTOP_CONFIG;
let app;
const launch=async()=>{app=await electron.launch({executablePath,args:[resolve('.')],env});const page=await app.firstWindow();await page.locator('#connection-button').waitFor();await page.evaluate(()=>window.plowshare.request({action:'bootstrap'}));return page;};
const state=page=>page.evaluate(async()=>(await window.plowshare.request({action:'bootstrap'})).state);
const close=async()=>{await app.close();app=undefined;};
const journal=async()=>JSON.parse(await readFile(join(directory,'desktop-jobs.json'),'utf8'));
try{
 let page=await launch();
 await page.evaluate(base=>window.plowshare.request({action:'connect',base,handle:'fixture',password:'fixture-password'}),fixture.base);
 await page.evaluate(()=>window.plowshare.request({action:'run',agent:'fixture-bot',text:'Work that survives closing the desktop',conversation:'fixture-first'}));
 const id=fixture.latestJob;
 await expect.poll(async()=>JSON.stringify(await journal())).toContain(id);
 await close();
 assert.equal(Object.values((await journal()).accounts).flat()[0].handle,id);
 fixture.completeLatest('Completed while the desktop was closed.');
 page=await launch();
 await expect.poll(async()=>(await state(page)).jobs.find(row=>row.id===id)?.status).toBe('finished');
 assert.equal(fixture.frames.filter(frame=>frame.type==='agent.run').length,1);
 assert.equal(fixture.loginCount(),1);
 assert.ok(fixture.frames.some(frame=>frame.type==='job.status'&&frame.payload.job===id));
 fixture.loseRunReply();
 await assert.rejects(page.evaluate(()=>window.plowshare.request({action:'run',agent:'fixture-bot',text:'Receipt lost before job acceptance',conversation:'fixture-first'})));
 await expect.poll(async()=>(await state(page)).jobs.some(row=>row.status==='unknown')).toBe(true);
 await expect.poll(async()=>Object.values((await journal()).accounts).flat().some(row=>!row.handle)).toBe(true);
 await close();page=await launch();
 await expect.poll(async()=>(await state(page)).jobs.some(row=>row.status==='unknown')).toBe(true);
 await assert.rejects(page.evaluate(()=>window.plowshare.request({action:'run',agent:'fixture-bot',text:'Must stay withheld',conversation:'fixture-first'})),/active|unknown|uncertain|running/i);
 assert.equal(fixture.frames.filter(frame=>frame.type==='agent.run').length,2);
 const serialized=JSON.stringify(await journal());assert.ok(!serialized.includes('fixture-access')&&!serialized.includes('fixture-refresh')&&!serialized.includes('Work that survives'));
 console.log('PASS: fresh desktop process restores saved job handles and completion without a new login or resubmission; missing acceptance survives restart and blocks duplicate work.');
}finally{if(app)await close();await fixture.close();await rm(directory,{recursive:true,force:true});}
