import { _electron as electron, expect } from 'playwright/test';
import executablePath from 'electron';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';
const profile = await mkdtemp(join(tmpdir(), 'plowshare-runs-smoke-'));
const fixture = await protocolFixture();
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(profile, 'credentials'), PLOWSHARE_DESKTOP_CONFIG: join(profile, 'config'), PLOWSHARE_DESKTOP_PROFILE: profile }; delete env.ELECTRON_RUN_AS_NODE;
let app;
try {
  app = await electron.launch({ executablePath, args: [resolve('.')], env });
  const main = await app.firstWindow(), errors = [];
  main.on('pageerror', error => errors.push(error.message));
  await main.locator('#connection-button').click();
  await main.locator('#server-url').fill(fixture.base); await main.locator('#handle').fill('fixture'); await main.locator('#password').fill('fixture-password');
  await main.locator('#submit-connection').click(); await expect(main.locator('#connection-label')).toHaveText('Connected');
  const opened = app.waitForEvent('window'); await main.evaluate(() => window.plowshare.request({ action: 'activity', view: 'runs' }));
  let runs = await opened; const runPage=runs; runs.on('pageerror', error => errors.push(error.message));
  await expect(runs.locator('#activity-title')).toHaveText('Runs'); await expect(runs.locator('.run-record')).toHaveCount(0); await expect(runs.locator('.run-detail-header #run-cancel-confirm')).toBeEnabled();
  await expect(runs.locator('#run-answer-send')).toBeEnabled();
  await runs.locator('[data-choice="0"] input[value="Archives"]').check(); await runs.locator('[data-choice="0"] [data-note]').fill('Read the original materials.');
  fixture.publish({ kind: 'orchestration.recorded', root: 'fixture-old-root', through: 125 });
  await expect(runs.locator('[data-choice="0"] input[value="Archives"]')).toBeChecked(); await expect(runs.locator('[data-choice="0"] [data-note]')).toHaveValue('Read the original materials.');
  await mkdir('build/smoke', { recursive: true }); await runs.screenshot({ path: 'build/smoke/run-question.png' });
  await runs.setViewportSize({ width: 860, height: 620 }); await runs.locator('#activity-detail').evaluate(node => { node.scrollTop = 0; }); await expect(runs.locator('.run-detail-header #run-cancel-confirm')).toBeInViewport(); await runs.screenshot({ path: 'build/smoke/run-question-compact.png' }); await runs.setViewportSize({ width: 1160, height: 800 });
  await runs.locator('[data-question-defer]').click(); await expect(runs.locator('.run-question')).toContainText('Deferred');
  assert.equal(fixture.frames.some(frame => frame.type === 'orchestration.answer'), false);
  await runs.locator('[data-question-resume]').click(); await expect(runs.locator('[data-choice="0"] input[value="Archives"]')).toBeChecked();
  assert.equal(await runs.evaluate(() => window.fixtureInjection), undefined);
  const trajectoryOpening = app.waitForEvent('window'); await runs.locator('[data-run-actor="conductor"]').click(); const trajectory = await trajectoryOpening; trajectory.on('pageerror', error => errors.push(error.message));
  await expect(trajectory.locator('body')).toContainText('Conductor research notes.'); await assert.rejects(trajectory.evaluate(() => window.plowshare.request({ action: 'run-cancel', id: 'fixture-old-root' })), /only read/); await trajectory.close();
  await assert.rejects(main.evaluate(() => window.plowshare.request({ action: 'run-cancel', id: 'fixture-old-root' })), /Open Activity/);
  await assert.rejects(runs.evaluate(() => window.plowshare.request({ action: 'run-trajectory', id: 'foreign', actor: 'conductor' })), /available/);
  const before = fixture.frames.filter(frame => frame.type === 'orchestration.answer').length;
  fixture.replaceQuestion(); await runs.locator('#run-answer-send').click(); await expect(runs.locator('#activity-error')).toContainText('changed'); assert.equal(fixture.frames.filter(frame => frame.type === 'orchestration.answer').length, before);
  await runs.locator('[data-choice="0"] input[value="Archives"]').check(); await runs.locator('#run-answer-send').click(); await expect(runs.locator('.run-notice')).toContainText('Answer recorded.'); await expect(runs.locator('#run-answer-send')).toHaveCount(0);
  const sent = fixture.frames.filter(frame => frame.type === 'orchestration.answer'); assert.equal(sent.length, 1); assert.deepEqual(sent[0].payload.choices, [{ header: 'Sources', chosen: ['Archives'] }]); assert.equal(fixture.frames.some(frame => frame.type === 'agent.run'), false);
  const studioOpening=app.waitForEvent('window');await main.evaluate(()=>window.plowshare.request({action:'activity',view:'definitions'}));runs=await studioOpening; await expect(runs.locator('#activity-title')).toHaveText('Definitions');
  await runs.locator('[data-item="unavailable_workflow"]').click(); await expect(runs.locator('#activity-detail')).toContainText('Required bot is unavailable'); await runs.locator('[data-item="deep_research"]').click(); await expect(runs.locator('#activity-detail')).toContainText('Sources collected');
  await mkdir('build/smoke', { recursive: true }); await runs.screenshot({ path: 'build/smoke/run-definitions.png' });
  await main.locator('#runs-open').click();runs=runPage; await expect(runs.locator('#activity-title')).toHaveText('Runs'); await expect(runs.locator('.run-record')).toHaveCount(0); await runs.screenshot({ path: 'build/smoke/run-header.png' });
  await runs.locator('.run-detail-header #run-cancel-confirm').click(); await expect(runs.locator('.run-notice')).toContainText('cancelled'); await expect(runs.locator('#run-cancel-confirm')).toHaveCount(0); assert.equal(fixture.frames.filter(frame => frame.type === 'orchestration.cancel').length, 1);
  fixture.changeRun('fixture-old-root', 'failed');
  await expect(runs.locator('.run-detail-header #run-resume')).toBeEnabled();
  await runs.locator('#run-resume').click();
  await expect(runs.locator('.run-notice')).toContainText('Resume request recorded.');
  await expect(runs.locator('#run-resume')).toHaveCount(0);
  const resumed = fixture.frames.filter(frame => frame.type === 'orchestration.resume');
  assert.equal(resumed.length, 1); assert.equal(resumed[0].payload.id, 'fixture-old-root');
  assert.match(resumed[0].payload.requestId, /^[0-9a-f-]{36}$/);
  const scheduleOpening=app.waitForEvent('window');await main.locator('#schedules-open').click();runs=await scheduleOpening; await expect(runs.locator('#activity-title')).toHaveText('Scheduled work');
  await runs.locator('#schedule-text').fill('Read the original sources every morning at 9am'); await runs.locator('#schedule-zone').fill('Australia/Melbourne');
  await runs.locator('#schedule-preview').click(); await expect(runs.locator('.schedule-proposal')).toContainText('Server-computed next fire times');
  assert.equal(fixture.frames.some(frame => frame.type === 'schedule.define'), false);
  await runs.locator('#schedule-action-kind').selectOption('skill');
  await runs.locator('#schedule-command').fill('review'); await runs.locator('#schedule-mode').selectOption('NEW');
  await runs.locator('#schedule-input').fill('Exact skill arguments\nKeep this newline');
  await runs.locator('#schedule-target-kind').selectOption('message'); await runs.locator('#schedule-route').fill('review-route');
  await runs.screenshot({ path: 'build/smoke/schedule-proposal.png' });
  await runs.locator('#schedule-save').click(); assert.deepEqual(fixture.frames.find(frame => frame.type === 'schedule.save').payload.definition.action,{kind:'skill',agent:'fixture-bot',name:'review',input:'Exact skill arguments\nKeep this newline',mode:'NEW'}); await expect(runs.locator('.run-notice')).toContainText('monitoring this folder');
  await runs.locator('[data-item="[\\"schedule\\",\\"fixture-morning\\"]"]').click();
  await runs.locator('#schedule-input').fill('Updated exact arguments'); await runs.locator('#schedule-file-update').click();
  await expect(runs.locator('.run-notice')).toContainText('monitoring this folder');
  assert.equal(fixture.frames.filter(frame => frame.type === 'schedule.save').length,2);
  assert.equal(fixture.frames.filter(frame => frame.type === 'schedule.save').at(-1).payload.overwrite,true);
  await runs.locator('[data-schedule-pause]').click(); await expect(runs.locator('#activity-detail header')).toContainText('Paused');
  await runs.locator('[data-schedule-pause]').click(); await expect(runs.locator('#activity-detail header')).toContainText('Active');
  await runs.locator('[data-item="[\\"trigger\\",\\"fixture-morning\\"]"]').click();
  await runs.locator('details').filter({ hasText: 'Emit this event now' }).locator('summary').click(); await runs.locator('[data-schedule-fire]').click(); await expect(runs.locator('.run-notice')).toContainText('Event emitted');
  await runs.screenshot({ path: 'build/smoke/scheduled-trigger.png' });
  await runs.locator('details').filter({ hasText: 'Remove this trigger' }).locator('summary').click(); await runs.locator('[data-schedule-remove]').click();
  await expect(runs.locator('[data-item]').filter({ hasText: 'fixture-morning' })).toHaveCount(0);
  await runs.locator('details').filter({hasText:'Monitored folders and file status'}).locator('summary').click();
  await runs.locator('#schedule-sync').click(); await expect(runs.locator('.run-notice')).toContainText('registered and reconciled');
  assert.equal(fixture.frames.filter(frame => frame.type === 'schedule.sync').length,1);
  await runs.locator('[data-item=""]').click(); await runs.locator('#schedule-preview').click(); fixture.setRefuseTriggerDefinition(true); await runs.locator('#schedule-save').click();
  await expect(runs.locator('#activity-error')).toContainText('Fixture bot unavailable');
  assert.equal(fixture.frames.filter(frame => frame.type === 'schedule.save').length, 3);
  assert.equal(fixture.frames.filter(frame => frame.type === 'schedule.define' || frame.type === 'trigger.define').length, 0);
  await runs.locator('#activity-refresh').click(); await expect(runs.locator('[data-item]').filter({ hasText: 'fixture-morning' })).toHaveCount(0);
  assert.equal(fixture.frames.some(frame => frame.type === 'agent.run'), false);
  assert.deepEqual(errors, []); console.log('PASS: native WS definitions, header cancellation, preserved question drafts, stale-answer guard, explicit answer/cancel scoped actor trajectories, scheduled-work preview/save/pause/resume/removal/event firing and file-save refusal without replay.');
} finally { if (app) await app.close(); await fixture.close(); await rm(profile, { recursive: true, force: true }); }
