import { _electron as electron, expect } from 'playwright/test';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { protocolFixture } from './protocol-fixture.mjs';

const profile = await mkdtemp(join(tmpdir(), 'plowshare-desktop-smoke-'));
await mkdir('build/smoke', { recursive: true });
const env = { ...process.env, PLOWSHARE_CONFIG_DIR: join(profile, 'credentials'), PLOWSHARE_DESKTOP_CONFIG: join(profile, 'config'), PLOWSHARE_DESKTOP_PROFILE: profile };
delete env.ELECTRON_RUN_AS_NODE;
const fixture = await protocolFixture();
let app;
try {
  const packaged = process.env.PLOWSHARE_PACKAGED_EXECUTABLE;
  const executablePath = packaged ?? (await import('electron')).default;
  app = await electron.launch({ executablePath, args: packaged ? [] : [resolve('.')], env });
  if (packaged) {
    assert.equal(await app.evaluate(({ app }) => app.getName()), 'Plowshare');
    assert.equal(await app.evaluate(() => process.execPath), packaged);
  }
  const page = await app.firstWindow();
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  // Capture only fixture writes; never read or replace the user's clipboard.
  await app.evaluate(({ clipboard }) => {
    clipboard.writeText = text => { globalThis.fixtureCopiedText = text; };
  });
  const copiedText = () => app.evaluate(() => globalThis.fixtureCopiedText);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.locator('#chat-title')).toHaveText('The peaceful atom');
  await expect(page.locator('.brand .app-icon')).toBeVisible();
  await expect(page.locator('.brand strong')).toHaveText('Plowshare');
  await expect(page.locator('.titlebar .breadcrumb')).toBeVisible();
  for (const id of ['navigation-open', 'refresh', 'inspector-toggle', 'connection-button']) await expect(page.locator(`.titlebar #${id}`)).toBeVisible();
  await expect(page.locator('.workspace-top, .workspace-footer')).toHaveCount(0);
  await page.waitForFunction(() => document.querySelector('.app-icon')?.naturalWidth > 0);
  await expect(page.locator('.titlebar-name')).toHaveCount(0);
  await expect(page.locator('.message.answer .message-label').first()).toContainText('Assistant');
  await expect(page.locator('#run-indicator')).toBeHidden();
  await expect(page.locator('#run-pace')).toBeHidden();
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  assert.equal(await page.evaluate(() => typeof window.process), 'undefined');
  assert.equal(await page.evaluate(() => typeof window.plowshare.request), 'function');
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences().sandbox), true);
  await expect(page.locator('.markdown-body h3')).toHaveText('Three reading threads');
  await expect(page.locator('.markdown-body table')).toHaveCount(1);
  await expect(page.locator('.markdown-body pre code')).toContainText('Proposal → Experiment → Evidence');
  await expect(page.locator('#context-label')).toContainText('Sample · Last turn peak · 15.2k / 131.1k · 11%');
  const code = page.locator('.markdown-code').first();
  const codeText = await code.locator('pre code').textContent();
  await code.hover();
  await code.locator('[data-copy="code"]').click();
  await expect(code.locator('[data-copy="code"]')).toHaveAccessibleName('Copied');
  assert.equal(await copiedText(), codeText, 'Code copying preserves displayed spacing without its language label.');
  await page.screenshot({ path: 'build/smoke/copy-controls.png' });
  const answer = page.locator('.message.answer').last();
  const answerMarkdown = await answer.getAttribute('data-copy-source');
  await answer.locator('.message-label').hover();
  await answer.locator('[data-copy="answer"]').click();
  await expect(answer.locator('[data-copy="answer"]')).toHaveAccessibleName('Copied');
  assert.equal(await copiedText(), answerMarkdown, 'Answer copying preserves the Markdown source.');
  assert.ok(answerMarkdown.includes('```') && answerMarkdown.includes('**'), 'The fixture exercises Markdown fences and emphasis.');
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'copy-text', text: 42 })), /Copy text must be a string/);
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'copy-text', text: 'x'.repeat(1048577) })), /at most 1,048,576/);
  assert.equal(await copiedText(), answerMarkdown, 'Invalid copy requests must not write.');
  await page.locator('.markdown-body table').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'build/smoke/desktop.png' });

  await page.locator('#draft').focus();
  await page.keyboard.press('Control+k');
  await expect(page.locator('#navigation-query')).toBeFocused();
  await page.keyboard.press('ArrowDown');
  assert.ok(await page.locator('#navigation-query').getAttribute('aria-activedescendant'), 'Keyboard navigation exposes the selected result.');
  const countBeforePalette = await page.locator('#conversation-count').textContent();
  await page.keyboard.press('Control+n');
  await expect(page.locator('#conversation-count')).toHaveText(countBeforePalette);
  await page.locator('#navigation-query').fill('no matching loaded name 49241');
  await expect(page.locator('.navigation-result')).toHaveCount(0);
  await page.keyboard.press('Enter');
  await expect(page.locator('#navigation-dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('#draft')).toBeFocused();
  await page.keyboard.press('Control+k');
  await page.locator('#navigation-query').fill('A workspace for everything');
  await page.keyboard.press('Enter');
  await expect(page.locator('#chat-title')).toHaveText('A workspace for everything');
  await expect(page.locator('[data-project="Plowshare"]')).toHaveAttribute('aria-current', 'true');
  await page.keyboard.press('Control+k');
  await page.locator('#navigation-query').fill('The peaceful atom');
  await page.keyboard.press('Enter');
  await expect(page.locator('#chat-title')).toHaveText('The peaceful atom');
  await page.keyboard.press('Control+k');
  await page.locator('#navigation-query').fill('Connection settings');
  await page.keyboard.press('Enter');
  await expect(page.locator('#connection-dialog')).toBeVisible();
  await page.keyboard.press('Control+k');
  await expect(page.locator('#navigation-dialog')).toBeHidden();
  await page.locator('#close-dialog').click();

  await page.locator('#dock').click();
  await expect(page.locator('#chat')).toHaveClass(/docked/);
  await page.locator('#dock').click();
  await page.locator('#chat-grip').press('ArrowRight');
  assert.notEqual(await page.locator('#chat').evaluate(node => getComputedStyle(node).transform), 'none');
  await page.locator('#expand').click();
  await expect(page.locator('#inspector')).toBeHidden();
  await page.locator('#expand').click();
  await expect(page.locator('#inspector')).toBeVisible();
  assert.equal(await page.locator('.execution-summary').count(), 0, 'Execution must not be appended below the chat.');
  assert.equal(await page.locator('#tab-execution').count(), 0, 'Trajectory is not an inspector tab.');
  const trajectoryOpened = app.waitForEvent('window');
  await page.locator('#trajectory-open').click();
  const trajectory = await trajectoryOpened;
  await expect(trajectory.locator('#trajectory-title')).toHaveText('The peaceful atom');
  await expect(trajectory.locator('#trajectory-rows')).toContainText('document_search');
  await trajectory.locator('.trajectory-row.call').first().click();
  await expect(trajectory.locator('#trajectory-detail-heading')).toContainText('document_search');
  await expect(trajectory.locator('#trajectory-detail-content')).toContainText('Sample library references');
  await expect(trajectory.locator('#trajectory-detail-content')).toContainText('Input');
  await expect(trajectory.locator('#trajectory-detail-content')).toContainText('Result');
  for (const section of await trajectory.locator('.trajectory-text-section').all()) {
    const displayedText = await section.locator('pre').textContent();
    await section.locator('[data-copy="section"]').click();
    await expect(section.locator('[data-copy="section"]')).toHaveAccessibleName('Copied');
    assert.equal(await copiedText(), displayedText, 'Trajectory sections copy their displayed input or result.');
  }
  const record = trajectory.locator('.trajectory-raw');
  const displayedRecord = await record.locator('pre').textContent();
  await record.locator('[data-copy="record"]').click();
  await expect(record.locator('[data-copy="record"]')).toHaveAccessibleName('Copied');
  assert.equal(await copiedText(), displayedRecord);
  assert.equal(await record.evaluate(node => node.open), false, 'Copying must not toggle record details.');
  await expect(trajectory.locator('#trajectory-follow')).toHaveAttribute('aria-pressed', 'false');
  await assert.rejects(trajectory.evaluate(() => window.plowshare.request({ action: 'run', conversation: 'demo-research', agent: 'plowshare', text: 'Should not run' })), /only read their own conversation/);
  await assert.rejects(trajectory.evaluate(() => window.plowshare.request({ action: 'history', conversation: 'demo-desktop' })), /only read their own conversation/);
  assert.equal(await trajectory.evaluate(() => typeof window.require), 'undefined');
  await trajectory.screenshot({ path: 'build/smoke/trajectory.png' });
  await page.locator('#title-caption').click();
  await page.locator('#trajectory-open').click();
  assert.equal((await app.windows()).length, 2, 'Opening again reuses the same trajectory window.');
  await trajectory.locator('#trajectory-search').fill('document_search');
  await expect(trajectory.locator('.trajectory-row')).toHaveCount(1);
  await trajectory.locator('#trajectory-search').fill('');
  await trajectory.locator('#trajectory-filter').selectOption('tools');
  await expect(trajectory.locator('.trajectory-row')).toHaveCount(1);
  await trajectory.locator('#trajectory-filter').selectOption('all');
  await trajectory.locator('#trajectory-rows').press('Home');
  await expect(trajectory.locator('#trajectory-detail-heading')).toContainText('User');
  await trajectory.locator('#trajectory-follow').click();
  await expect(trajectory.locator('#trajectory-detail-heading')).toContainText('Assistant');

  await page.locator('#title-caption').click();
  const shortDraftHeight = await page.locator('#draft').evaluate(node => node.getBoundingClientRect().height);
  await page.locator('#draft').fill('A long draft line\n'.repeat(50));
  const longDraftHeight = await page.locator('#draft').evaluate(node => node.getBoundingClientRect().height);
  assert.ok(longDraftHeight > shortDraftHeight && longDraftHeight <= 160, 'Long drafts grow within a bounded composer.');
  await page.locator('#draft').fill('Draft for research');
  assert.equal(await page.locator('#draft').evaluate(node => node.getBoundingClientRect().height), shortDraftHeight, 'Short drafts shrink the composer again.');
  await page.locator('[data-project="Plowshare"]').click();
  await expect(page.locator('#chat-title')).toHaveText('A workspace for everything');
  await expect(trajectory.locator('#trajectory-title')).toHaveText('The peaceful atom');
  await page.locator('#draft').fill('A different draft');
  await page.locator('[data-project="Research"]').click();
  await expect(page.locator('#draft')).toHaveValue('Draft for research');
  await trajectory.close();
  await page.keyboard.press('Control+b');
  await expect(page.locator('#sidebar')).toBeHidden();
  await page.reload();
  await expect(page.locator('#draft')).toHaveValue('Draft for research');
  await expect(page.locator('#sidebar')).toBeHidden();
  await page.locator('#sidebar-toggle').click();
  await expect(page.locator('#sidebar')).toBeVisible();

  await page.locator('#send').click();
  await expect(page.locator('#run-indicator')).toBeVisible();
  await expect(page.locator('#run-indicator')).toHaveAttribute('data-phase', 'thinking');
  await page.locator('#new-conversation').click();
  await page.locator('#draft').fill('A second running conversation');
  await page.locator('#send').click();
  await expect(page.locator('#running-count')).toHaveText('2');
  await page.locator('#cancel').click();
  await expect(page.locator('#composer-status')).toHaveText('Ready');
  await expect(page.locator('#run-indicator')).toBeHidden();
  await expect(page.locator('#conversation-alerts')).toContainText('Run stopped · cancelled');
  await expect(page.locator('#transcript .message.summary')).toHaveCount(0);
  await expect(page.locator('.conversation-alert')).toHaveCount(1);

  await page.locator('#connect-sidebar').click();
  await page.locator('#server-url').fill(fixture.base);
  await page.locator('#handle').fill('fixture');
  await page.locator('#password').fill('wrong-password');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connect-error')).toContainText('Sign-in failed. Check your handle and password.');
  await page.locator('#password').fill('fixture-password');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-dialog')).not.toBeVisible();
  await expect(page.locator('#connection-label')).toHaveText('Connected');
  const sourceOpening=app.waitForEvent('window');await page.locator('#library-open').click();
  const sourcePage=await sourceOpening;sourcePage.on('pageerror',error=>errors.push(error.message));
  await sourcePage.locator('#library-documents').click();await sourcePage.locator('#document-sources > summary').click();
  const library=sourcePage.locator('#document-source-panel');
  await expect(library).toBeVisible();await library.locator('[data-add-open]').click();await expect(library.locator('[data-add-dialog]')).toBeVisible();await expect(library.locator('[data-add] [name="name"]')).toBeFocused();await library.locator('[data-add-close]').click();await expect(library.locator('[data-add-dialog]')).not.toBeVisible();
  await library.locator('.information-row').click();
  await expect(library.locator('[data-passage]')).toContainText('A retained claim.');await sourcePage.screenshot({path:'build/smoke/library-sources.png'});
  assert.equal(await library.locator('img').count(),0,'Retained source HTML is displayed as text.');
  await library.locator('[data-passage]').evaluate(node=>{node.focus();node.setSelectionRange(0,16);});
  await library.locator('[data-record-evidence]').click();
  await expect(library.locator('[data-new-evidence]')).toContainText('bbbbbbbb-0000-0000-0000-000000000002');
  const evidenceFrame=fixture.frames.find(frame=>frame.type==='information.evidence.record');
  assert.equal(evidenceFrame.payload.start,0);assert.equal(evidenceFrame.payload.end,16);
  assert.equal(evidenceFrame.payload.quote,'A retained claim');assert.ok(evidenceFrame.payload.requestId);
  await library.locator('[data-ask] input').fill('What does it establish?');
  await library.locator('[data-refresh]').click();await expect(library.locator('[data-ask] input')).toHaveValue('What does it establish?');
  await library.locator('[data-ask] input').press('Enter');await library.locator('[data-ask]').dispatchEvent('submit');
  await expect(library.locator('[data-answer]')).toContainText('Grounded answer from retained evidence.',{timeout:12000});assert.equal(fixture.frames.filter(frame=>frame.type==='information.ask').length,1);await expect(library.locator('[data-ask] input')).toHaveValue('What does it establish?');
  await sourcePage.screenshot({path:'build/smoke/information-library.png'});
  await library.getByText('Manage source',{exact:true}).click();
  await library.locator('[data-control="share"]').click();
  await expect(library.locator('[data-error]')).toContainText('A source was withdrawn.');
  await library.locator('[data-scope]').selectOption('shared');
  await expect(library.locator('[data-list]')).toContainText('No sources');
  await expect(library.locator('[data-detail]')).not.toContainText('Grounded answer');
  await sourcePage.close();
  await expect(page.locator('#chat-title')).toHaveText('Fixture conversation');
  await expect(page.locator('#transcript')).toContainText('Loaded through the real TypeScript WebSocket binding.');
  await expect(page.locator('#context-label')).toHaveText('Last turn peak · 15.2k / 131.1k · 11%');
  await expect(page.locator('#inbox-count')).toHaveText('25');
  await expect(page.locator('#runs-count')).toHaveText('1');
  assert.equal(fixture.frames.some(frame => frame.type === 'inbox.read'), false, 'Startup count reads cannot mark unseen deliveries.');
  const activityWindow = app.waitForEvent('window');
  await page.locator('#inbox-open').click();
  let activityPage = await activityWindow; const inboxPage=activityPage;
  activityPage.on('pageerror', error => errors.push(error.message));
  await expect(activityPage.locator('#activity-title')).toHaveText('Mailbox');
  await expect(activityPage.locator('#inbox-filter')).toHaveValue('unread');
  await expect(activityPage.locator('#inbox-type')).toHaveValue('');
  await activityPage.locator('#inbox-type').selectOption('run');
  await expect(activityPage.locator('.activity-row')).toHaveCount(1);
  await activityPage.locator('#inbox-filter').selectOption('read');
  await expect(activityPage.locator('.activity-row')).toHaveCount(0);
  await expect(activityPage.locator('#activity-detail')).not.toContainText('background research result');
  await activityPage.locator('#inbox-type').selectOption('');
  await activityPage.locator('#inbox-filter').selectOption('unread');
  await expect(activityPage.locator('.activity-row')).toHaveCount(20);
  await expect(activityPage.locator('#activity-detail strong')).toContainText(['background research result']);
  await expect(activityPage.locator('#activity-detail table')).toHaveCount(1);
  assert.equal(fixture.frames.some(frame => frame.type === 'inbox.read'), false, 'Opening and rendering the inbox is not a read receipt.');
  await activityPage.screenshot({ path: 'build/smoke/inbox.png' });
  await activityPage.locator('#inbox-filter').selectOption('all');
  fixture.setRefuseReceipts(true);
  await activityPage.locator('#inbox-mark').click();
  await expect(activityPage.locator('#activity-error')).toContainText('Fixture receipt refused');
  await expect(activityPage.locator('#activity-detail')).toContainText('background research result');
  await expect(page.locator('#inbox-count')).toHaveText('25');
  fixture.setRefuseReceipts(false);
  await activityPage.locator('#inbox-mark').click();
  await expect(activityPage.locator('#inbox-mark')).toHaveText('Marked read');
  await expect(page.locator('#inbox-count')).toHaveText('24');
  await expect(activityPage.locator('#activity-detail')).toContainText('background research result');
  const receiptCount = fixture.frames.filter(frame => frame.type === 'inbox.read').length;
  await activityPage.locator('#inbox-filter').selectOption('unread');
  await expect(activityPage.locator('.activity-row')).toHaveCount(19);
  await expect(activityPage.locator('[data-item="fixture-inbox-1"]')).toHaveCount(0);
  await expect(activityPage.locator('#activity-detail')).not.toContainText('background research result');
  await activityPage.locator('#inbox-filter').selectOption('read');
  await expect(activityPage.locator('.activity-row')).toHaveCount(1);
  await expect(activityPage.locator('#inbox-mark')).toBeDisabled();
  await expect(page.locator('#inbox-count')).toHaveText('24');
  await activityPage.locator('#activity-search').fill('does not match');
  await expect(activityPage.locator('.activity-row')).toHaveCount(0);
  await expect(activityPage.locator('#activity-list')).toContainText('No matching items.');
  await expect(activityPage.locator('#inbox-mark')).toHaveCount(0);
  await activityPage.locator('#activity-search').fill('');
  await activityPage.locator('#inbox-filter').selectOption('all');
  await activityPage.locator('[data-item="fixture-inbox-1"]').click();
  await activityPage.locator('#activity-refresh').click();
  await expect(activityPage.locator('[data-item="fixture-inbox-1"]')).toContainText('Read');
  await expect(activityPage.locator('#inbox-mark')).toHaveText('Marked read');
  await activityPage.locator('#inbox-older').click();
  await expect(activityPage.locator('.activity-row')).toHaveCount(26);
  await expect(activityPage.locator('[data-item="fixture-inbox-21"]')).toBeVisible();
  await activityPage.locator('[data-item="fixture-already-read"]').click();
  await expect(activityPage.locator('#activity-detail')).toContainText('already read in another session');
  await expect(activityPage.locator('#inbox-mark')).toBeDisabled();
  await expect(activityPage.locator('#inbox-older')).toBeHidden();
  await activityPage.screenshot({ path: 'build/smoke/inbox-read-history.png' });
  await activityPage.locator('#inbox-filter').selectOption('read');
  await expect(activityPage.locator('.activity-row')).toHaveCount(2);
  await activityPage.screenshot({ path: 'build/smoke/inbox-filter.png' });
  await activityPage.locator('#activity-refresh').click();
  await expect(activityPage.locator('#inbox-filter')).toHaveValue('read');
  await expect(activityPage.locator('.activity-row')).toHaveCount(2);
  await activityPage.locator('#inbox-filter').selectOption('unread');
  await expect(activityPage.locator('.activity-row')).toHaveCount(24);
  await activityPage.locator('#inbox-filter').selectOption('all');
  for (const [kind, label] of [['approval', 'Approval'], ['orchestration', 'Orchestration'], ['hook', 'Hook notice'], ['sync.conflict', 'Sync conflict'], ['custom.audit', 'custom.audit']]) {
    await activityPage.locator('#inbox-type').selectOption(kind);
    await expect(activityPage.locator('.activity-row')).toHaveCount(1);
    await expect(activityPage.locator('.activity-row strong')).toHaveText(label);
  }
  await activityPage.locator('#activity-search').fill('Fixture notice 6');
  await expect(activityPage.locator('.activity-row')).toHaveCount(1);
  await activityPage.locator('#activity-search').fill('Fixture notice 2');
  await expect(activityPage.locator('.activity-row')).toHaveCount(0);
  await activityPage.locator('#activity-search').fill('');
  await activityPage.locator('#inbox-type').selectOption('approval');
  await activityPage.locator('#activity-refresh').click();
  await expect(activityPage.locator('#inbox-type')).toHaveValue('approval');
  await expect(activityPage.locator('.activity-row')).toHaveCount(1);
  await expect(page.locator('#inbox-count')).toHaveText('24');
  assert.equal(fixture.frames.filter(frame => frame.type === 'inbox.read').length, receiptCount, 'Type and status filtering cannot receipt messages.');
  await activityPage.screenshot({ path: 'build/smoke/inbox-type-filter.png' });
  await activityPage.locator('#inbox-type').selectOption('');
  await activityPage.locator('#inbox-filter').selectOption('unread');
  assert.equal(fixture.frames.filter(frame => frame.type === 'inbox.read').length, receiptCount);
  fixture.addInboxNotice();
  await expect(page.locator('#inbox-count')).toHaveText('25');
  await expect(activityPage.locator('#activity-list')).toContainText('An inbox notice from another session.');
  const runOpening=app.waitForEvent('window');await page.locator('#runs-open').click();activityPage=await runOpening;activityPage.on('pageerror',error=>errors.push(error.message));
  await expect(activityPage.locator('#activity-title')).toHaveText('Runs');
  await expect(activityPage.locator('#inbox-filter-control')).toBeHidden();
  await expect(activityPage.locator('[data-item="fixture-old-root"]')).toBeVisible();
  await expect(activityPage.locator('#activity-detail')).toContainText('Which sources should we read next?');
  await expect(activityPage.locator('#activity-detail')).toContainText('Archives');
  await activityPage.screenshot({ path: 'build/smoke/runs.png' });
  await assert.rejects(activityPage.evaluate(() => window.plowshare.request({ action: 'run', conversation: 'fixture-first', agent: 'fixture-bot', text: 'Unauthorized test' })), /Activity windows can only/);
  await assert.rejects(activityPage.evaluate(() => window.plowshare.request({ action: 'inbox-read', id: 'fixture-inbox-25' })), /displayed/);
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'inbox-read', id: 'fixture-inbox-1' })), /Open Activity/);
  await activityPage.locator('[data-run="fixture-child-1"]').click();
  await expect(activityPage.locator('#activity-detail')).toContainText('A completed child result.');
  await activityPage.locator('[data-run="fixture-old-root"]').click();
  await expect(activityPage.locator('#activity-detail')).toContainText('Which sources should we read next?');
  fixture.changeRun('fixture-old-root', 'running');
  await expect(activityPage.locator('#activity-detail>header')).toContainText('running');
  fixture.setRefuseRuns(true);
  await activityPage.locator('#activity-refresh').click();
  await expect(activityPage.locator('#activity-error')).toContainText('Fixture live state unavailable');
  await expect(activityPage.locator('[data-item="fixture-old-root"]')).toBeVisible();
  fixture.setRefuseRuns(false);
  await activityPage.locator('#activity-refresh').click();
  await expect(activityPage.locator('#activity-error')).toBeHidden();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 700));
  assert.equal(await activityPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await activityPage.screenshot({ path: 'build/smoke/activity-compact.png' });
  await activityPage.close();await inboxPage.close();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 960));
  assert.equal(fixture.frames.some(frame => frame.type === 'orchestration.cancel'), false);
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'conversation.follow').at(-1)?.payload.conversations).toEqual(['fixture-first']);
  const subscribedWindow = app.waitForEvent('window');
  await page.locator('#trajectory-open').click();
  const subscribedTrajectory = await subscribedWindow;
  await expect(subscribedTrajectory.locator('#trajectory-title')).toHaveText('Fixture conversation');
  const otherConversation = await page.evaluate(async () => (await window.plowshare.request({ action: 'create' })).conversation);
  await page.locator(`[data-conversation="${otherConversation}"]`).click();
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'conversation.follow').at(-1)?.payload.conversations).toEqual(['fixture-first', otherConversation].sort());
  fixture.appendTurn('fixture-first', 'Inspection later result.');
  fixture.appendTurn(otherConversation, 'Main chat later result.');
  await expect(subscribedTrajectory.locator('#trajectory-detail-content')).toContainText('Inspection later result.');
  await expect(page.locator('#transcript')).toContainText('Main chat later result.');
  await expect(page.locator('#transcript')).toContainText('Harness · orchestration fixture-run');
  await expect(page.locator('#transcript')).not.toContainText('Inspection later result.');
  await subscribedTrajectory.close();
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'conversation.follow').at(-1)?.payload.conversations).toEqual([otherConversation]);
  fixture.appendTurn('fixture-first', 'Inspection later result.');
  await page.locator('[data-conversation="fixture-first"]').click();
  await expect(page.locator('.message.answer').filter({ hasText: 'Inspection later result.' })).toHaveCount(2);
  assert.equal(fixture.frames.some(frame => frame.type === 'job.cancel'), false);
  fixture.setSupportsFollowing(false);
  await page.locator('#refresh').click();
  await expect(page.locator('#conversation-alerts')).toContainText('Live updates unavailable');
  await expect(page.locator('#connection-label')).toHaveText('Connected');
  await page.screenshot({ path: 'build/smoke/subscription-warning.png' });
  fixture.setSupportsFollowing(true);
  await page.locator('#refresh').click();
  await expect(page.locator('#conversation-alerts')).not.toContainText('Live updates unavailable');
  await page.locator('[data-context-details="identity"] summary').click();
  await expect(page.locator('[data-context-details="identity"]')).toContainText('fixture-first');
  assert.equal(await page.locator('#context-meter').evaluate(node => node.value), 11);
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'open-link', url: 'javascript:alert(1)' })), /Only http or https/);
  fixture.setContext({ sent: null, prefix: { model: 'fixture-model', contextLength: 131072 } });
  await page.locator('#refresh').click();
  await expect(page.locator('#context-label')).toHaveText('Context not measured · max 131.1k');
  await expect(page.locator('#context-meter')).toBeHidden();
  fixture.setContext({ sent: 124000, prefix: { model: 'fixture-model', contextLength: 131072 } });
  await page.locator('#refresh').click();
  await expect(page.locator('#conversation-alerts')).toContainText('Last turn approached limit');
  await expect(page.locator('#context-label')).toHaveText('Last turn peak · 124k / 131.1k · 94%');
  assert.equal(await page.locator('[data-context-details="identity"]').evaluate(node => node.open), true, 'Context refreshes preserve open details.');
  await page.screenshot({ path: 'build/smoke/context-alert.png' });
  fixture.setContext({ sent: 15240, prefix: { model: 'fixture-model', contextLength: 131072 } });
  await page.locator('#refresh').click();
  await expect(page.locator('#conversation-alerts')).not.toContainText('Last turn approached limit');

  assert.equal(await page.locator('#transcript img').count(), 0, 'Model output must not become executable markup.');
  assert.equal(await page.evaluate(() => window.fixtureInjection), undefined);
  await assert.rejects(page.evaluate(() => window.plowshare.request({ action: 'ask', type: 'project.forget' })), /Unsupported desktop action/);
  assert.equal(JSON.stringify(await page.evaluate(() => window.plowshare.request({ action: 'bootstrap' }))).includes('fixture-access'), false, 'The renderer must not receive credentials.');
  await expect(page.locator('#conversations')).not.toContainText('The peaceful atom');
  await expect(page.locator('#approval-bar')).toContainText('echo fixture approval');
  await page.locator('[data-decision="once"]').click();
  await expect(page.locator('#transcript')).toContainText('Fixture streaming: Approval once: fixture-approval');
  await page.locator('#cancel').click();
  await expect(page.locator('#composer-status')).toHaveText('Ready');
  await expect(page.locator('#approval-bar')).toBeHidden();
  await page.locator('[data-project="Empty workspace"]').click();
  await page.locator('#draft').fill('Create a conversation with my first message');
  await expect(page.locator('#send')).toBeEnabled();
  await page.locator('#send').click();
  await expect(page.locator('#transcript')).toContainText('Fixture streaming: Create a conversation with my first message');
  const orchestrationAnswer = '`orc_3198AD04B3828AF1` (`deep_research`) is working; its result will be delivered to you when it finishes.';
  fixture.commitLatest(orchestrationAnswer);
  await expect.poll(() => page.evaluate(async () => Object.values((await window.plowshare.request({ action: 'bootstrap' })).state.history).some(history => history.entries.some(entry => entry.text?.includes('orc_3198AD04B3828AF1'))))).toBe(true);
  await expect(page.locator('#transcript .message.answer')).toHaveCount(1);
  await expect(page.locator('#transcript')).not.toContainText('orc_3198AD04B3828AF1');
  const completedTrajectoryOpened = app.waitForEvent('window');
  await page.locator('#trajectory-open').click();
  const completedTrajectory = await completedTrajectoryOpened;
  await expect(completedTrajectory.locator('#trajectory-run')).toBeVisible();
  await expect(completedTrajectory.locator('#trajectory-detail-heading')).toContainText('Live response');
  await page.locator('#title-caption').click();
  fixture.completeLatest(orchestrationAnswer, { toolCalls: 0, reasoningTokens: 20, reasoningEstimated: true,
    completionTokens: 72, firstTokenMillis: 431, tokensPerSecond: 34.4 });
  await expect(page.locator('#composer-status')).toHaveText('Ready');
  await expect(page.locator('#run-indicator')).toBeHidden();
  await expect(page.locator('#transcript .message.answer')).toHaveCount(1);
  await expect(page.locator('#transcript .message.answer code')).toHaveText(['orc_3198AD04B3828AF1', 'deep_research']);
  await expect(page.locator('#transcript .message.summary')).toHaveCount(0);
  await expect(page.locator('#conversation-alerts')).toBeHidden();
  await expect(page.locator('#run-pace')).toBeVisible();
  await expect(page.locator('[data-pace="tools"]')).toHaveText('0');
  await expect(page.locator('[data-pace="tools"]')).toHaveAttribute('aria-label', '0 tool calls');
  await expect(page.locator('[data-pace="thinking"]')).toHaveText('think ~20');
  await expect(page.locator('[data-pace="responding"]')).toHaveText('out 72');
  await expect(page.locator('[data-pace="waiting"]')).toHaveText('ttft 431ms');
  await expect(page.locator('[data-pace="speed"]')).toHaveText('34 tok/s');
  await expect(page.locator('#run-pace .pace-stat')).toHaveCount(5);
  await page.screenshot({ path: 'build/smoke/answered.png' });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 700));
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), { message: 'Pace statistics must fit compact windows after the native resize settles.' }).toBe(true);
  assert.equal(await page.locator('#composer').evaluate(node => node.getBoundingClientRect().bottom <= window.innerHeight), true);
  await page.screenshot({ path: 'build/smoke/pace-compact.png' });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 960));
  await expect(completedTrajectory.locator('#trajectory-rows')).toContainText('orc_3198AD04B3828AF1');
  await expect(completedTrajectory.locator('.step-kind').filter({ hasText: 'Run outcome' })).toHaveCount(0);
  await expect(completedTrajectory.locator('#trajectory-rows [data-step^="event:"]')).toHaveCount(0);
  await expect(completedTrajectory.locator('#trajectory-run')).toBeHidden();
  await expect(completedTrajectory.locator('#trajectory-detail-heading')).toContainText('Assistant');
  const completedRows = await completedTrajectory.locator('.trajectory-row').count();
  await expect(completedTrajectory.locator('#trajectory-summary')).toContainText(`${completedRows} steps`);
  await expect(completedTrajectory.locator('#trajectory-diagnostics')).not.toHaveAttribute('open');
  await completedTrajectory.locator('#trajectory-diagnostics > summary').click();
  await completedTrajectory.locator('#trajectory-diagnostics-content summary').last().click();
  await expect(completedTrajectory.locator('#trajectory-diagnostics-content pre').last()).toBeVisible();
  await expect(completedTrajectory.locator('#trajectory-diagnostics-content pre').last()).toContainText('"kind": "ended"');
  await completedTrajectory.screenshot({ path: 'build/smoke/trajectory-diagnostics.png' });
  await completedTrajectory.close();
  await page.locator('[data-project=""]').click();
  await expect(page.locator('#chat-title')).toHaveText('Fixture conversation');
  await expect(page.locator('#run-pace')).toBeHidden();
  const projectRosters = fixture.frames.filter(frame => frame.type === 'agent.list' && frame.payload.project === 'Empty workspace').length;
  await page.keyboard.press('Control+k');
  await page.locator('#navigation-query').fill('Create a conversation with my first message');
  await page.keyboard.press('Enter');
  await expect(page.locator('[data-project="Empty workspace"]')).toHaveAttribute('aria-current', 'true');
  await expect(page.locator('#agent')).toHaveValue('fixture-bot');
  await expect(page.locator('#run-pace')).toBeVisible();
  await expect(page.locator('[data-pace="thinking"]')).toHaveText('think ~20');
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'agent.list' && frame.payload.project === 'Empty workspace').length).toBeGreaterThan(projectRosters);
  await page.keyboard.press('Control+k');
  await page.locator('#navigation-query').fill('Fixture conversation');
  await page.keyboard.press('Enter');
  await expect(page.locator('#chat-title')).toHaveText('Fixture conversation');
  await page.locator('#draft').fill('First live task');
  await page.locator('#send').click();
  await expect(page.locator('#transcript')).toContainText('Fixture streaming: First live task');
  await expect(page.locator('#run-indicator')).toHaveAttribute('data-phase', 'answer');
  await expect(page.locator('.stream-caret')).toBeVisible();
  const jobId = fixture.latestJob;
  fixture.publish({ job: jobId, part: 'THINKING', text: ' More published reasoning.' });
  await expect(page.locator('#composer-status')).toHaveText('Reasoning…');
  await expect(page.locator('#run-indicator')).toBeVisible();
  await expect(page.locator('#run-indicator')).toHaveAttribute('data-phase', 'thinking');
  await expect(page.locator('.stream-caret')).toHaveCount(0);
  const orbit = page.locator('.run-orbit');
  const animationTime = await orbit.evaluate(node => node.getAnimations()[0]?.currentTime ?? -1);
  assert.ok(animationTime >= 0, 'Thinking has a running native CSS animation.');
  await expect.poll(() => orbit.evaluate(node => node.getAnimations()[0]?.currentTime ?? -1)).toBeGreaterThan(animationTime);
  await orbit.evaluate(node => { node.fixtureAnimation = node.getAnimations()[0]; });
  fixture.publish({ job: jobId, part: 'THINKING', text: ' Still reasoning.' });
  await expect.poll(() => page.evaluate(id => window.plowshare.request({ action: 'bootstrap' }).then(reply => reply.state.jobs.find(job => job.id === id)?.thinking), jobId)).toContain('Still reasoning.');
  assert.equal(await orbit.evaluate(node => node.getAnimations()[0] === node.fixtureAnimation), true, 'A reasoning delta must not restart the mounted animation.');
  await page.screenshot({ path: 'build/smoke/thinking.png' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(page.locator('#run-indicator')).toBeVisible();
  assert.equal(await orbit.evaluate(node => node.getAnimations().length), 0, 'Reduced motion retains a still phase indicator.');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  fixture.publish({ job: jobId, kind: 'tool_called', tool: 'document_search' });
  await expect(page.locator('#composer-status')).toHaveText('Using document_search…');
  await expect(page.locator('.run-tool')).toBeVisible();
  await expect(page.locator('.stream-caret')).toHaveCount(0);
  fixture.publish({ job: jobId, part: 'ANSWER', text: ' Continued.' });
  await expect(page.locator('#composer-status')).toHaveText('Responding…');
  await expect(page.locator('.run-bars')).toBeVisible();
  await expect(page.locator('.stream-caret')).toBeVisible();
  const liveTrajectoryOpened = app.waitForEvent('window');
  await page.locator('#trajectory-open').click();
  const liveTrajectory = await liveTrajectoryOpened;
  await expect(liveTrajectory.locator('#trajectory-detail-content')).toContainText('Fixture streaming: First live task');
  await expect(liveTrajectory.locator('#trajectory-run')).toBeVisible();
  await expect(liveTrajectory.locator('#trajectory-rows [data-step^="event:"]')).toHaveCount(0);
  await expect(liveTrajectory.locator('#trajectory-rows [data-step^="job:"]')).toHaveCount(0);
  await liveTrajectory.locator('.trajectory-run-item').filter({ hasText: 'Live reasoning' }).click();
  await expect(liveTrajectory.locator('#trajectory-detail-content')).toContainText('Fixture reasoning: First live task');
  await expect(page.locator('#transcript')).not.toContainText('Fixture reasoning');
  await liveTrajectory.locator('#trajectory-follow').click();
  const liveRows = await liveTrajectory.locator('.trajectory-row').count();
  await liveTrajectory.locator('#trajectory-diagnostics > summary').click();
  const jobDiagnostics = liveTrajectory.locator(`#trajectory-diagnostics-content [data-job="${jobId}"]`);
  await jobDiagnostics.locator('summary').click();
  fixture.publish({ job: jobId, kind: 'model_call', agent: 'fixture-bot', modelCalls: 2 });
  fixture.publish({ job: jobId, kind: 'alive', agent: 'fixture-bot' });
  fixture.publish({ job: jobId, kind: 'alive', agent: 'fixture-bot' });
  await expect(liveTrajectory.locator('#trajectory-run-status')).toContainText('Reasoning…');
  await expect(jobDiagnostics).toHaveAttribute('open');
  await expect(jobDiagnostics.locator('pre')).toContainText('"kind": "alive"');
  await expect(liveTrajectory.locator('.trajectory-row')).toHaveCount(liveRows);
  await expect(liveTrajectory.locator('#trajectory-detail-heading')).toContainText('Live response');
  await jobDiagnostics.locator('[data-copy="record"]').click();
  await expect(jobDiagnostics.locator('[data-copy="record"]')).toHaveAccessibleName('Copied');
  const diagnosticCopy = JSON.parse(await copiedText());
  assert.equal(diagnosticCopy.job, jobId);
  assert.equal(diagnosticCopy.events.filter(event => event.kind === 'alive').length, 2,
    'Repeated heartbeats remain available in diagnostics without becoming timeline steps.');
  await liveTrajectory.locator('#trajectory-diagnostics > summary').click();
  await liveTrajectory.screenshot({ path: 'build/smoke/trajectory-live.png' });
  await page.locator('#new-conversation').click();
  await page.locator('#draft').fill('Second live task');
  await page.locator('#send').click();
  await expect(page.locator('#running-count')).toHaveText('2');
  await expect(page.locator('#transcript')).toContainText('Fixture streaming: Second live task');
  await expect(page.locator('#transcript')).not.toContainText('Fixture streaming: First live task');
  await expect(liveTrajectory.locator('#trajectory-detail-content')).not.toContainText('Second live task');
  await page.locator('#cancel').click();
  await expect(page.locator('#conversation-alerts')).toContainText('Run stopped · cancelled');
  await expect(page.locator('#transcript .message.summary')).toHaveCount(0);
  await expect(page.locator('.conversation-alert')).toHaveCount(1);
  const stoppedTrajectoryOpened = app.waitForEvent('window');
  await page.locator('#trajectory-open').click();
  const stoppedTrajectory = await stoppedTrajectoryOpened;
  await expect(stoppedTrajectory.locator('#trajectory-run-status')).toContainText('Run stopped');
  await expect(stoppedTrajectory.locator('#trajectory-detail-heading')).toContainText('Run outcome');
  await stoppedTrajectory.locator('#trajectory-filter').selectOption('failed');
  await expect(stoppedTrajectory.locator('.trajectory-run-item')).toContainText('Run outcome');
  await expect(stoppedTrajectory.locator('#trajectory-detail-content')).toContainText('Fixture run cancelled.');
  await expect(stoppedTrajectory.locator('#trajectory-diagnostics-content pre').last()).toContainText('Fixture run cancelled.');
  await stoppedTrajectory.close();
  await page.locator('#conversations [data-conversation="fixture-first"]').click();
  await expect(page.locator('#transcript')).toContainText('Fixture streaming: First live task');
  const reconnectActivityWindow = app.waitForEvent('window');
  await page.locator('#inbox-open').click();
  const reconnectActivity = await reconnectActivityWindow;
  reconnectActivity.on('pageerror', error => errors.push(error.message));
  await expect(reconnectActivity.locator('#activity-title')).toHaveText('Mailbox');
  fixture.disconnect();
  await expect(page.locator('#connection-label')).toContainText('Connection lost');
  await expect(reconnectActivity.locator('#activity-error')).toContainText('Reconnect');
  fixture.addInboxNotice();
  await expect(page.locator('#composer-status')).toHaveText('Outcome uncertain');
  await expect(page.locator('#run-indicator')).toBeHidden();
  await expect(page.locator('.stream-caret')).toHaveCount(0);
  await expect(page.locator('#conversation-alerts')).toContainText('Outcome uncertain');
  await expect(page.locator('#context-label')).toContainText('Last measured');
  await expect(liveTrajectory.locator('#trajectory-detail-heading')).toContainText('unknown');
  await expect(page.locator('#send')).toBeDisabled();
  assert.equal(fixture.frames.filter(frame => frame.type === 'agent.run').length, 3);
  await expect(page.locator('#error')).not.toBeVisible();
  assert.equal(errors.length, 0, errors.join('\n'));

  fixture.appendTurn('fixture-first', 'A result delivered while disconnected.');
  await page.locator('#connect-sidebar').click();
  await page.locator('#password').fill('');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-label')).toHaveText('Connected');
  await expect(reconnectActivity.locator('#activity-list')).toContainText('An inbox notice from another session.');
  await expect(page.locator('#inbox-count')).toHaveText('26');
  await expect.poll(() => fixture.frames.filter(frame => frame.type === 'conversation.follow').at(-1)?.payload.conversations).toContain('fixture-first');
  await expect(liveTrajectory.locator('#trajectory-rows')).toContainText('A result delivered while disconnected.');
  await page.locator('#conversations [data-conversation="fixture-first"]').click();
  fixture.completeJob(jobId);
  await expect(page.locator('#transcript')).toContainText('A result delivered while disconnected.');
  const longAnswer = '# Practical steps\n\n' + 'Long explanation.\n'.repeat(6000)
    + '\n**A2A (Python)**\n\n```python\nprint("complete")\n```\nFinal line 🎉';
  fixture.appendTurn('fixture-first', longAnswer);
  const longMessage = page.locator('.message.answer').filter({ hasText: 'Final line 🎉' });
  await expect(longMessage).toHaveCount(1);
  await expect(longMessage.locator('code')).toHaveText('print("complete")\n');
  await expect(longMessage).not.toContainText('Excerpt shown');
  assert.equal(await longMessage.getAttribute('data-copy-source'), longAnswer,
    'Durable long answers retain their whole Markdown source.');
  await longMessage.locator('[data-copy="answer"]').click();
  assert.equal(await copiedText(), longAnswer, 'Copy includes the ending of a long answer.');
  assert.equal(fixture.frames.filter(frame => frame.type === 'agent.run').length, 3, 'Reconnect does not resubmit agent work.');

  await page.locator('#connect-sidebar').click();
  await page.locator('#password').fill('');
  await page.locator('#handle').fill('');
  await page.locator('#submit-connection').click();
  await expect(page.locator('#connection-label')).toContainText('Connected');
  assert.equal(fixture.loginCount(), 1, 'Reconnect uses the saved session instead of another password login.');
  await page.locator('#connect-sidebar').click();
  await page.locator('#use-demo').click();
  await expect.poll(() => liveTrajectory.isClosed()).toBe(true);
  await expect.poll(() => reconnectActivity.isClosed()).toBe(true);
  await page.locator('[data-project="Research"]').click();
  await page.locator('#conversations [data-conversation="demo-research"]').click();
  await expect(page.locator('#tab-context, #tab-memory, #tab-usage')).toHaveCount(0);
  await page.locator('.markdown-body table').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'build/smoke/desktop.png' });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 700));
  await expect(page.locator('#chat')).toBeVisible();
  assert.equal(await page.locator('#composer').evaluate(node => node.getBoundingClientRect().bottom <= window.innerHeight), true, 'Composer must fit inside the native window.');
  assert.equal(await page.locator('.chat-header').evaluate(node => node.getBoundingClientRect().height >= 60), true, 'The title and controls must not collapse in a compact window.');
  for (const id of ['navigation-open', 'refresh', 'inspector-toggle', 'connection-button']) {
    assert.equal(await page.locator(`#${id}`).evaluate(node => { const bounds = node.getBoundingClientRect(); return bounds.top >= 0 && bounds.bottom <= 52 && bounds.right <= innerWidth; }), true, 'Window controls must fit the titlebar in compact windows.');
  }
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.locator('#transcript').evaluate(node => { node.scrollTop = 0; });
  await expect(page.locator('#jump-latest')).toBeVisible();
  await page.locator('#jump-latest').click();
  await expect(page.locator('#jump-latest')).toBeHidden();
  await page.locator('.markdown-body table').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'build/smoke/compact.png' });
  const chatWidth = await page.locator('#chat').evaluate(node => node.getBoundingClientRect().width);
  await page.locator('#inspector-toggle').click();
  await expect(page.locator('#inspector')).toBeVisible();
  assert.equal(await page.locator('#chat').evaluate(node => node.getBoundingClientRect().width), chatWidth, 'The compact context drawer must not squeeze chat.');
  await page.screenshot({ path: 'build/smoke/context-drawer.png' });
  await page.keyboard.press('Control+k');
  await expect(page.locator('#navigation-dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('#navigation-dialog')).toBeHidden();
  await expect(page.locator('#inspector')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('#inspector')).toBeHidden();
  await expect(page.locator('#inspector-toggle')).toBeFocused();
  await page.locator('#inspector-toggle').click();
  await page.locator('#inspector-close').click();
  await expect(page.locator('#inspector-toggle')).toHaveAttribute('aria-expanded', 'false');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 960));
  await page.locator('#new-conversation').click();
  await expect(page.locator('.empty-chat')).toBeVisible();
  await expect(page.locator('#new-conversation')).toBeEnabled();
  await page.screenshot({ path: 'build/smoke/empty.png' });
  await page.locator('[data-suggestion]').first().click();
  await expect(page.locator('#draft')).toHaveValue('Help me explore an idea and find useful sources.');
  await expect(page.locator('#draft')).toBeFocused();
  await page.locator('#sidebar-toggle').click();
  await page.screenshot({ path: 'build/smoke/focus.png' });
  await page.keyboard.press('Control+k');
  await page.screenshot({ path: 'build/smoke/navigator.png' });
  console.log('Electron smoke passed: isolated renderers, Markdown/context, embedded trajectory and account Activity pages, clean recorded-step timelines, separate live progress, collapsed copyable job diagnostics, completion follow and stopped outcomes, inbox badges/explicit receipts/refusals/read history/older pages/status and type filters, old active roots, child navigation, structured question inspection, guarded activity permissions, multi-view subscriptions, ordinal catch-up, later results, reconnect without replay, responsive layout, draft/navigation/copy controls, phase animation, canonical completion and scoped run pace and scoped information library/evidence/answers/refusals.');
  console.log('Screenshots: build/smoke/{desktop,trajectory,compact,context-alert,context-drawer,empty,focus,navigator,copy-controls,thinking,answered,pace-compact,subscription-warning,inbox,inbox-read-history,inbox-filter,inbox-type-filter,runs,activity-compact}.png');
} finally {
  await app?.close(); await fixture.close(); await rm(profile, { recursive: true, force: true });
}
