import {_electron as electron, expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {protocolFixture} from './protocol-fixture.mjs';
const profile=await mkdtemp(join(tmpdir(),'plowshare-usage-')), fixture=await protocolFixture({conversationProject:'Usage test'});
fixture.addServerProject({name:'Usage test'});
const env={...process.env,PLOWSHARE_DESKTOP_PROFILE:profile,PLOWSHARE_DESKTOP_CONFIG:join(profile,'config'),PLOWSHARE_CONFIG_DIR:join(profile,'credentials')};delete env.ELECTRON_RUN_AS_NODE;
let app;
try {
  const packaged=process.env.PLOWSHARE_PACKAGED_EXECUTABLE,executablePath=packaged??(await import('electron')).default;
  app=await electron.launch({executablePath,args:packaged?[]:[resolve('.')],env});const main=await app.firstWindow(), errors=[];
  main.on('pageerror',e=>errors.push(e.message));
  await main.evaluate(base=>window.plowshare.request({action:'connect',base,handle:'fixture',password:'fixture-password'}),fixture.base);
  await main.locator('[data-project="Usage test"]').click();
  await main.locator('#conversations [data-conversation="fixture-first"]').click();
  await expect(main.locator('#inspector-content')).toContainText('Constructed projection');
  await expect(main.locator('#tab-memory, #tab-usage')).toHaveCount(0);
  await main.locator('#draft').fill('An unsent draft that must never enter context');
  await main.locator('[data-context-details="message-0"] > summary').click();
  await expect(main.locator('[data-context-details="message-0"] pre')).toContainText('Use retained evidence. <img');
  assert.equal(await main.evaluate(()=>window.fixtureInjection),undefined);
  await main.locator('#context-refresh').click();
  await expect(main.locator('#inspector-content')).not.toContainText('An unsent draft');
  assert.ok(fixture.frames.filter(f=>f.type==='conversation.context.snapshot').every(f=>Object.keys(f.payload).sort().join(',')==='agent,conversation,measure'));
  assert.equal(fixture.frames.filter(f=>f.type==='conversation.context.snapshot'&&f.payload.measure).length,0);
  await main.locator('#context-count').click();await expect(main.locator('#inspector-content')).toContainText('765');
  await main.locator('[data-context-details="schemas"] > summary').click();await expect(main.locator('[data-context-details="schemas"]')).toContainText('lookup');
  fixture.setRefuseSnapshot(true);await main.locator('#context-refresh').click();await expect(main.locator('#inspector-content [role="alert"]')).toContainText('last snapshot');fixture.setRefuseSnapshot(false);await main.locator('#context-count').click();await expect(main.locator('#inspector-content [role="alert"]')).toHaveCount(0);
  await mkdir('build/smoke',{recursive:true});await main.screenshot({path:'build/smoke/current-context.png'});
  await main.locator('#connect-sidebar').click();const opening=app.waitForEvent('window');await main.locator('#connection-usage').click();const usage=await opening;usage.on('pageerror',e=>errors.push(e.message));
  await expect(main.locator('#title-caption')).toHaveText('Usage');await expect(main.locator('#usage-open')).toHaveAttribute('aria-current','page');
  await expect(main.locator('#inspector')).toBeHidden();
  await expect(usage.locator('[data-usage-report]')).toContainText('Input tokens2,400');
  await expect(usage.locator('[data-usage-type]')).toHaveValue('usage.models');
  await expect(usage.locator('[data-usage-count]')).toHaveCount(0);
  assert.ok((await usage.locator('.usage-screen').boundingBox()).width>650,'Usage uses the main workspace width.');
  await main.evaluate(()=>{
    window.fixtureStageTransitions=[];
    const stage=document.querySelector('#stage');
    window.fixtureStageObserver=new MutationObserver(rows=>window.fixtureStageTransitions.push(...rows.map(row=>row.oldValue)));
    window.fixtureStageObserver.observe(stage,{attributes:true,attributeFilter:['hidden'],attributeOldValue:true});
    window.fixtureProjectRow=document.querySelector('[data-project="Usage test"]');
    window.fixtureAgentOption=document.querySelector('#agent option');
    window.fixtureUsageInputs=[];
    window.plowshare.subscribe(state=>window.fixtureUsageInputs.push(state.usage?.report?.totals.input_tokens));
  });
  for(const tokens of ['3500','3550','3600']) {
    fixture.publishUsage(tokens);
    await expect(usage.locator('[data-usage-report]')).toContainText(`Input tokens${Number(tokens).toLocaleString('en-US')}`);
    await expect.poll(()=>main.evaluate(value=>window.fixtureUsageInputs.includes(value),tokens)).toBe(true);
  }
  assert.equal(await main.evaluate(()=>window.fixtureStageTransitions.includes(null)),false,'Background updates must not reveal hidden chat beneath a workspace page.');
  assert.equal(await main.evaluate(()=>window.fixtureProjectRow===document.querySelector('[data-project="Usage test"]')),true,'Unchanged project navigation stays mounted.');
  assert.equal(await main.evaluate(()=>window.fixtureAgentOption===document.querySelector('#agent option')),true,'Unchanged agent options stay mounted.');

  fixture.setRefuseUsage(true);await usage.getByRole('button',{name:'Refresh usage',exact:true}).click();await expect(usage.locator('[data-usage-status]')).toContainText('Usage capture is unavailable');await expect(usage.locator('[data-usage-report]')).toContainText('Input tokens3,600');
  fixture.setRefuseUsage(false);fixture.setUsageCapture(false);await main.locator('#refresh').click();await expect(usage.locator('[data-usage-status]')).toContainText('Usage recording is disabled on this server');await expect(usage.locator('[data-usage-status]')).toContainText('do not measure past activity');
  fixture.setUsageCapture(true);await main.locator('#refresh').click();await expect(usage.locator('[data-usage-report]')).toContainText('Input tokens2,400');
  await expect(usage.getByRole('tab')).toHaveText(['Overview','Calls','Pricing','Recording']);
  await expect(usage.locator('[data-usage-view="overview"]')).toBeVisible();
  await expect(usage.locator('[data-usage-view="pricing"]')).toBeHidden();
  await usage.getByRole('tab',{name:'Pricing',exact:true}).click();
  await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.00144');
  const beforeComparison=fixture.frames.length;
  await usage.locator('[data-usage-provider]').selectOption('Anthropic');
  await expect(usage.locator('[data-usage-price]')).toHaveValue('anthropic-sonnet-5.5');
  await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.0078');
  await usage.locator('[data-usage-price]').selectOption('anthropic-opus-5.5');
  await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.0156');
  await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.01234');
  await usage.locator('[data-usage-provider]').selectOption('custom');
  await usage.locator('[data-usage-input]').fill('1');await usage.locator('[data-usage-input]').dispatchEvent('change');
  await usage.locator('[data-usage-output]').fill('2');await usage.locator('[data-usage-output]').dispatchEvent('change');
  await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.003');
  assert.equal(fixture.frames.length,beforeComparison,'Comparisons do not make server requests.');
  fixture.publishUsage('3600');await expect(usage.locator('[data-usage-comparison]')).toContainText('USD 0.0042');
  await expect(usage.locator('[data-usage-view="pricing"]')).toBeVisible();
  await usage.screenshot({path:'build/smoke/usage-pricing.png'});
  await usage.getByRole('tab',{name:'Calls',exact:true}).click();await expect(usage.locator('[data-usage-view="calls"]')).toContainText('No recorded calls');
  assert.ok(fixture.frames.some(f=>f.type==='usage.calls'));
  await usage.getByRole('tab',{name:'Recording',exact:true}).click();await expect(usage.locator('[data-usage-recording]')).toContainText('On · automatic');
  await usage.getByRole('tab',{name:'Overview',exact:true}).click();
  await usage.screenshot({path:'build/smoke/usage.png'});
  await main.setViewportSize({width:700,height:850});
  assert.equal(await usage.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,'No horizontal overflow on a narrow desktop window.');

  await fixture.disconnect();await expect(usage.locator('#usage-connection')).toContainText('Disconnected');
  await main.evaluate(base=>window.plowshare.request({action:'connect',base,handle:'fixture',password:''}),fixture.base);
  await expect(usage.locator('[data-usage-status]')).toContainText('Live usage snapshot');
  await main.locator('#conversations [data-conversation="fixture-first"]').click();await main.locator('#usage-open').click();await expect(main.locator('#title-caption')).toHaveText('Usage');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);
  await assert.rejects(usage.evaluate(()=>window.plowshare.request({action:'run',conversation:'fixture-first',agent:'fixture-bot',text:'forbidden'})),/Usage can only read/);
  assert.deepEqual([...new Set(fixture.httpPaths)].sort(),['/v1/auth/login','/v1/auth/refresh','/v1/auth/ticket']);assert.deepEqual(errors,[]);
  console.log('PASS: repeated live Usage updates keep chat hidden and unchanged project navigation and agent controls mounted. Tabbed Usage with local provider/model and custom cost comparisons, live comparison updates, readable coverage, and narrow layout. Full-size Usage from Connection and sidebar, initial and replacement snapshots, visible capture-disabled/errors, retained data and reconnect. Context preserves constructed text/tool schemas, excludes draft, counts only explicitly, and retains failed snapshots. All operational traffic uses WS.');
} finally {await app?.close();await fixture.close();await rm(profile,{recursive:true,force:true});}
