import type { DesktopState, Request } from '../shared.ts';
import { emptyLibrary, libraryIdentity, memoryIdentity, type LibraryView, type SearchKind } from '../library-shared.ts';
import type { RetrievalReplies, LogSearchResponse, PassageCoverage } from 'plowshare-client-ts/operations/retrieval';
import { mountIcons, icon } from './icons.ts';
import { escapeHtml as esc, markdownHtml } from './markdown.ts';
import { copyButton, installCopyControls } from './copy.ts';
mountIcons(); installCopyControls();
const $ = <T extends HTMLElement = HTMLElement>(selector:string):T => document.querySelector(selector)!;
let state:DesktopState, stamp='', localError='', identity='', selectedProposal='';
const drafts = new Map<string,string>();
const disclosures = new Map<string,boolean>();
const prose = (text:string) => `<div class="message-content" data-copy-source="${esc(text)}">${copyButton('Copy text','answer')}${markdownHtml(text)}</div>`;
const coverage = (value: PassageCoverage | null | undefined) => value ? `Coverage: ${value.indexed} indexed / ${value.eligible} eligible; ${value.passages} passages; ${value.pending} pending, ${value.failed} failed, ${value.stale} stale.` : 'Index coverage was not reported by this server.';
const status = (slot:{loading?:boolean;stale?:boolean;error?:string}) => `${slot.stale?'<p class="library-note">Previous snapshot · refresh or submit a new search.</p>':''}${slot.loading?'<p class="library-note">Reading…</p>':''}${slot.error?`<p class="error-banner">${esc(slot.error)}</p>`:''}`;
async function action(request:Request) { try { const reply=await window.plowshare.request(request); localError=''; update(reply.state); } catch(error) { localError=error instanceof Error?error.message:String(error); render(); } }
function update(next:DesktopState) { const nextIdentity=JSON.stringify([next.base,next.handle,next.mode]); if(identity!==nextIdentity){drafts.clear();disclosures.clear();selectedProposal='';stamp='';identity=nextIdentity;} state=next; render(); }
function remember() { for(const detail of document.querySelectorAll<HTMLDetailsElement>('[data-library-disclosure]')) disclosures.set(detail.dataset.libraryDisclosure!,detail.open); for(const input of document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-library-draft]')) drafts.set(input.dataset.libraryDraft!,input.value); }
function restore() { for(const detail of document.querySelectorAll<HTMLDetailsElement>('[data-library-disclosure]')) detail.open=disclosures.get(detail.dataset.libraryDisclosure!)??false; for(const input of document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-library-draft]')) input.value=drafts.get(input.dataset.libraryDraft!)??''; }
function render() {
 if(!state)return; const v=state.library??emptyLibrary(); remember();
 $('#library-connection').textContent=state.mode==='demo'?'Offline demo · connect to read Library':`${state.connection} · ${state.handle}`;
 const errors=[localError,v.error,!state.connected?'Reconnect in the main window. Shown information may be out of date.':''].filter(Boolean);
 $('#library-error').hidden=!errors.length; $('#library-error').textContent=errors.join(' '); $('#library-notice').hidden=!v.notice; $('#library-notice').textContent=v.notice??'';
 for(const tab of ['documents','memories','search']){const button=$(`#library-${tab}`);button.setAttribute('aria-selected',String(v.view===tab));button.tabIndex=v.view===tab?0:-1;}
 $('#library-panel').setAttribute('aria-labelledby',`library-${v.view}`);$('#library-panel').classList.toggle('search-view',v.view==='search');
 $('#document-filter').hidden=v.view!=='documents';$('#search-form').hidden=v.view!=='search';$('#library-scope-label').hidden=v.view==='documents';
 $('#library-scope-note').textContent=v.view==='documents'?'Documents belong to the server corpus. PDF and image conversion runs on the server.':`Memory and conversation reads use ${v.project??'Global'}. Document searches use the server corpus.${v.view==='memories'?' Reading a memory records a use.':''}`;
 const scope=$<HTMLSelectElement>('#library-scope'); const options='<option value="">Global</option>'+state.projects.map(row=>`<option value="${esc(row.name)}">${esc(row.name)}</option>`).join(''); if(scope.innerHTML!==options)scope.innerHTML=options;scope.value=v.project??'';scope.disabled=!!v.busy;
 $('#library-refresh').toggleAttribute('disabled',!state.connected||!!v.busy);
 const next=JSON.stringify([v,selectedProposal,state.connected]);if(stamp===next)return;stamp=next;
 const results=$('#library-results'),detail=$('#library-detail'),scroll=detail.scrollTop;
 if(v.view==='documents') {
  results.innerHTML=status(v.documents)+(v.documents.value?`<p class="library-note">${v.documents.value.documents.length} / ${v.documents.value.total} documents${v.documents.query?` · ${esc(v.documents.query)}`:''}</p>${v.documents.value.naming?`<p>${esc(v.documents.value.naming)}</p>`:''}${v.documents.value.documents.map(row=>`<button class="library-row ${v.document.id===row.documentId?'selected':''}" data-document="${esc(row.documentId)}"><strong>${esc(row.title||row.sourceName)}</strong><small>${esc(row.sourceName)} · ${row.byteSize.toLocaleString()} bytes<br>${row.chapters} chapters · ${row.sections} sections · ${row.paragraphs} paragraphs · ${row.chunks} passages</small></button>`).join('')}${v.documents.value.documents.length<v.documents.value.total?'<button id="documents-more">Load more documents</button>':''}`:'<p class="activity-empty">Find documents in the server corpus.</p>');
  detail.innerHTML=documentDetail();
 } else if(v.view==='memories') {
  results.innerHTML=status(v.memories)+(v.memories.value?`<h3>${v.memories.value.length} memories</h3>${v.memories.value.map(row=>`<button class="library-row ${v.memory.id===row.id?'selected':''}" data-memory="${esc(row.id)}"><strong>${esc(row.summary||row.id)}</strong><small>${esc(row.scope)} · ${row.unsearchable===true?'Not searchable':row.unsearchable===false?'Searchable':'Searchability not reported'}</small></button>`).join('')}`:'')+status(v.proposals)+`<h3>Proposals</h3>${v.proposals.value?.map(row=>`<button class="library-row ${selectedProposal===row.id?'selected':''}" data-proposal="${esc(row.id)}"><strong>${esc(row.action)} · ${esc(row.state)}</strong><small>${esc(row.reason)}</small></button>`).join('')||'<p>No proposals loaded.</p>'}<details class="library-maintenance" data-library-disclosure="${esc('maintain:'+v.project)}"><summary>Maintain ${esc(v.project??'Global')}</summary><p>Repair missing embeddings, or reopen rejected proposals for this scope. Each action changes server state once.</p><button data-maintain="reembed" ${v.busy?'disabled':''}>Repair embeddings</button><button data-maintain="reconsider" ${v.busy?'disabled':''}>Reconsider rejected proposals</button></details>`;
  const proposal=v.proposals.value?.find(row=>row.id===selectedProposal);
  detail.innerHTML=proposal?`<header><div class="eyebrow">${esc(proposal.project??'Global')} · ${esc(proposal.state)}</div><h2>${esc(proposal.action)} proposal</h2><p class="library-source">${esc(proposal.id)} · ${esc(proposal.createdAt)} · ${esc(proposal.proposedBy)}</p></header>${prose(proposal.reason)}<button data-memory="${esc(proposal.memoryId)}">Read source memory</button>${proposal.resolution?prose(proposal.resolution):''}${proposal.state==='pending'?`<div class="library-form"><label>Resolution reason<textarea id="proposal-reason" data-library-draft="${esc('proposal:'+libraryIdentity(proposal))}"></textarea></label><p>Accept applies this proposal to the memory archive. Reject records your decision.</p><div class="library-actions"><button data-resolve="true" ${v.busy?'disabled':''}>Accept proposal</button><button data-resolve="false" ${v.busy?'disabled':''}>Reject proposal</button></div></div>`:''}`:memoryDetail();
 } else { results.innerHTML=searchResults(); detail.innerHTML=v.selected==='chunk'?chunkDetail():v.selected==='memory'?memoryDetail():v.selected==='document'?documentDetail():'<p class="activity-empty">Choose a source from the search results.</p>'; }
 restore(); detail.scrollTop=scroll;
}
function documentDetail() {
 const v=state.library??emptyLibrary(),d=v.document.value;if(!d)return status(v.document)+'<p class="activity-empty">Choose a document to read its outline, or search for passages.</p>';
 return status(v.document)+`<header><div class="eyebrow">Server corpus</div><h2>${esc(d.title||d.sourceName)}</h2><p class="library-source">${esc(d.sourceName)} · ${esc(d.documentId)}<br>Ingested ${esc(d.ingestedAt)} by ${esc(d.ingestedBy)} · ${d.byteSize.toLocaleString()} bytes</p></header>${d.summary?prose(d.summary):''}${d.vocabulary?`<section><h3>Vocabulary</h3>${prose(d.vocabulary)}</section>`:''}<section><h3>Outline</h3><ul class="library-outline">${d.chapters.map(ch=>`<li><strong>${esc(ch.title??'Synthetic chapter')}</strong><small class="library-source"> · ${esc(ch.id)}</small>${ch.summary?prose(ch.summary):''}${ch.sections.map(sec=>`<div><h4>${esc(sec.title??'Synthetic section')}</h4><small class="library-source">${esc(sec.id)}</small>${sec.summary?prose(sec.summary):''}</div>`).join('')}</li>`).join('')}</ul></section><button id="document-citations">Read recent citations</button>${status(v.citations)}${v.citations.value?`<section><h3>${v.citations.value.citations.length} recent citations · ${esc(v.citations.value.scope)}</h3>${v.citations.value.citations.map(c=>`<article class="library-hit"><strong>${esc(c.standing)}</strong><p class="library-source">${esc(c.sourceName)} · paragraph ${c.paragraphOrdinal}<br>${esc(c.agent)} · ${esc(c.citedAt)}<br>Conversation ${esc(c.conversationId??'not recorded')} · turn ${c.turnOrdinal??'not recorded'}</p>${c.paragraphText?prose(c.paragraphText):'<p>Original paragraph is unavailable.</p>'}</article>`).join('')}</section>`:''}<details class="library-maintenance" data-library-disclosure="${esc('claim:'+d.documentId)}"><summary>Compare this document to a claim</summary><div class="library-form"><label>Claim<textarea id="document-claim" data-library-draft="${esc('claim:'+d.documentId)}"></textarea></label><p>This computes topicality and stance on the server.</p><button id="document-stance">Check claim</button></div>${status(v.stance)}${v.stance.value?`<p>${esc(v.stance.value.claim)}</p><p>Topicality ${v.stance.value.topical}; stance ${v.stance.value.stance}; basis ${esc(v.stance.value.basis)}</p>`:''}</details>`;
}
function memoryDetail() {
 const v=state.library??emptyLibrary(),m=v.memory.value;if(!m)return status(v.memory)+'<p class="activity-empty">Choose a memory or proposal.</p>';
 return status(v.memory)+`<header><div class="eyebrow">${esc(m.home.project??'Global')} · ${esc(m.state)}${m.pinned?' · pinned':''}</div><h2>${esc(m.summary||m.id)}</h2><p class="library-source">${esc(m.id)}<br>Formed ${esc(m.formed.at)} by ${esc(m.formed.by)} · ${esc(m.formed.where)}<br>${m.uses} uses · last used ${esc(m.lastUsed??'never')}</p></header><p>Applies to: ${esc(m.scope)}</p>${prose(m.body)}${m.supersedes?`<p>Supersedes ${esc(m.supersedes)}</p>`:''}${m.supersededBy?`<p>Superseded by ${esc(m.supersededBy)}</p>`:''}${m.invalidation?`<p>Invalidated ${esc(m.invalidation.at)} by ${esc(m.invalidation.by)}</p>${prose(m.invalidation.reason)}`:''}${m.state==='active'&&m.home.project===v.project?`<details class="library-maintenance" data-library-disclosure="${esc('invalidate:'+m.id)}"><summary>Invalidate this memory</summary><p>Marks this memory as invalid in the archive. Its body and provenance remain inspectable.</p><div class="library-form"><label>Reason<textarea id="memory-reason" data-library-draft="${esc('memory:'+memoryIdentity(m))}"></textarea></label><button id="memory-invalidate" ${v.busy?'disabled':''}>Confirm invalidation</button></div></details>`:''}`;
}
function chunkDetail() {const v=state.library??emptyLibrary(),c=v.chunk.value;return status(v.chunk)+(c?`<h2>${esc(c.title||c.sourceName)}</h2><p class="library-source">${esc(c.sourceName)} · paragraph ${c.paragraphOrdinal}<br>Document ${esc(c.documentId)}<br>Paragraph ${esc(c.paragraphId)} · passage ${esc(c.chunkId)}</p>${c.chapter?`<p>Chapter: ${esc(c.chapter.title??'Synthetic')}</p>`:''}${c.section?`<p>Section: ${esc(c.section.title??'Synthetic')}</p>`:''}${c.paragraphSummary?prose(c.paragraphSummary):''}${prose(c.text)}<button data-document="${esc(c.documentId)}">Read document outline</button>`:'<p>Reading passage…</p>');}
function searchResults() {
 const slot=state.library?.search,value=slot?.value;if(!value)return status(slot??{})+'<p class="activity-empty">Choose a method and submit a question.</p>';
 let html=status(slot!)+`<h3>${esc(value.query)}</h3><p class="library-note">${esc(value.kind)} · ${value.kind==='conversation'||value.kind==='recall'||value.kind==='navigate'?esc(value.project??'Global'):'Server corpus'}</p>`;
 if(value.kind==='conversation') {
  const r=value.reply as LogSearchResponse,meta=r.retrieval;
  html+=`<div class="library-coverage">${r.hits.length} loaded / ${r.total} ${esc(meta?.totalMeaning??'matches (meaning not reported)')}<br>${r.reach.searched} searched; ${r.reach.ejected} ejected; ${r.reach.recordedOnly} recorded only.<br>${meta?`Requested ${esc(meta.requestedMode)}; effective ${esc(meta.effectiveMode)} · ${meta.complete?'Complete':'Incomplete'}${meta.truncated?' · truncated':''}<br>Provenance: ${esc(meta.provenance)}<br>${esc(coverage(meta.coverage))}<br>Snapshot ${esc(meta.snapshot??'none')} · generation ${esc(meta.generation??'not reported')} · query embedding calls ${meta.queryEmbeddingCalls}${meta.fallback?`<br>Fallback: ${esc(meta.fallback)}`:''}`:'Retrieval provenance and completeness were not reported by this server.'}</div>`;
  html+=r.hits.map(hit=>`<article class="library-hit"><strong>${esc(hit.kind)} · entry ${hit.ordinal} · turn ${hit.turnOrdinal}</strong><p>${esc(hit.snippet)}</p><p class="library-source">${esc(hit.conversationId)} · ${esc(hit.handle??'speaker not recorded')} · rank ${hit.rank}${hit.supersededBy?` · superseded by entry ${hit.supersededBy}`:''}<br>${hit.evidence?`Retrieved by ${esc(hit.evidence.retrievedBy)} · passage ${hit.evidence.passagePosition??'not reported'} · source revision ${esc(hit.evidence.sourceRevision??'not reported')}`:'Evidence metadata not reported.'}</p><button data-conversation="${esc(hit.conversationId)}">Inspect trajectory ${icon('external')}</button></article>`).join('');
  if(r.hits.length<r.total&&(meta?.effectiveMode==='lexical'||!!meta?.snapshot))html+='<button id="search-more">Load more from this search</button>';
 } else if(value.kind==='documents') {
  const r=value.reply as RetrievalReplies['document.search'];html+=`<div class="library-coverage">Mode ${esc(r.mode??'not reported')}; ${r.searchable} searchable; ${r.unsearchable} unsearchable. Up to ${r.limit} hits.</div>`+r.hits.map(hit=>`<article class="library-hit"><strong>${esc(hit.title||hit.sourceName)} · paragraph ${hit.paragraphOrdinal}</strong><p>${esc(hit.paragraphText)}</p><p class="library-source">Similarity ${hit.similarity} · ${esc(hit.paragraphId)}</p><button data-chunk="${esc(hit.chunkId)}">Read passage</button><button data-document="${esc(hit.documentId)}">Document outline</button></article>`).join('');
 } else if(value.kind==='retrieve') {
  const r=value.reply as RetrievalReplies['document.retrieve'];html+=`<p>Up to ${r.limit} passages. Coverage metadata is not provided by this operation.</p>`+r.hits.map(hit=>`<article class="library-hit"><strong>${esc(hit.chunk.title||hit.chunk.sourceName)} · paragraph ${hit.chunk.paragraphOrdinal}</strong>${prose(hit.chunk.text)}<p>Score ${hit.score}</p><button data-chunk="${esc(hit.chunk.chunkId)}">Read source passage</button></article>`).join('');
 } else if(value.kind==='rank') {
  const r=value.reply as RetrievalReplies['document.rank'];html+=`<div class="library-coverage">${r.rankable} rankable documents; ${r.unranked} unranked.</div>`+r.documents.map(doc=>`<button class="library-row" data-document="${esc(doc.documentId)}"><strong>${esc(doc.title||doc.sourceName)}</strong><small>Score ${doc.score} · ${esc(doc.sourceName)}</small>${doc.summary?`<span>${esc(doc.summary)}</span>`:''}</button>`).join('');
 } else if(value.kind==='recall') {
  const r=value.reply as RetrievalReplies['memory.recall'];html+=`<div class="library-coverage">${r.memories.length} returned; ${r.unsearchable} unsearchable memories.</div>`+r.memories.map(m=>`<button class="library-row" data-memory="${esc(m.id)}"><strong>${esc(m.summary)}</strong><small>${esc(m.home.project??'Global')} · ${esc(m.state)} · formed by ${esc(m.formed.by)}</small><span>${esc(m.body)}</span></button>`).join('');
 } else {
  const r=value.reply as RetrievalReplies['memory.navigate'],meta=r.retrieval;html+=`<div class="library-coverage">${r.complete?'Complete':'Incomplete'} navigation · level ${esc(r.level)} · ${r.modelCalls} model calls.<br>${meta?`Tier ${esc(meta.tier)}; seed ${esc(meta.seedMode)}${meta.globalFallback?' · global fallback':''}<br>${esc(coverage(meta.coverage))}<br>Generation ${esc(meta.generation??'not reported')} · query embedding calls ${meta.queryEmbeddingCalls}${meta.fallback?`<br>Fallback: ${esc(meta.fallback)}`:''}`:'Retrieval coverage and provenance were not reported by this server.'}</div>${prose(r.text)}${r.ids.map(id=>`<button class="library-row" data-memory="${esc(id)}">Read memory ${esc(id)}</button>`).join('')}`;
 }
 return html;
}
for(const view of ['documents','memories','search'] as LibraryView[])$(`#library-${view}`).addEventListener('click',()=>{selectedProposal='';void action({action:'library-view',view,project:state.library?.project??null});});
for(const view of ['documents','memories','search'] as LibraryView[])$(`#library-${view}`).addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();const tabs:LibraryView[]=['documents','memories','search'],next=tabs[(tabs.indexOf(view)+(event.key==='ArrowRight'?1:2))%3];$(`#library-${next}`).focus();selectedProposal='';void action({action:'library-view',view:next,project:state.library?.project??null});}});
$('#library-scope').addEventListener('change',()=>{selectedProposal='';void action({action:'library-view',view:state.library?.view??'memories',project:$<HTMLSelectElement>('#library-scope').value||null});});
$('#library-refresh').addEventListener('click',()=>void action({action:'library-refresh'}));
$('#document-filter').addEventListener('submit',event=>{event.preventDefault();void action({action:'library-documents',query:$<HTMLInputElement>('#document-query').value});});
$('#search-form').addEventListener('submit',event=>{event.preventDefault();void action({action:'library-search',kind:$<HTMLSelectElement>('#search-kind').value as SearchKind,query:$<HTMLInputElement>('#search-query').value,mode:$<HTMLSelectElement>('#search-mode').value as 'lexical'|'semantic'|'hybrid'});});
$('#search-kind').addEventListener('change',()=>{$('#search-mode-label').hidden=!['conversation','documents'].includes($<HTMLSelectElement>('#search-kind').value);});
$('#library-panel').addEventListener('input',remember);
document.addEventListener('click',event=>{
 const target=event.target as HTMLElement,v=state?.library;if(!v)return;remember();
 const documentId=target.closest<HTMLElement>('[data-document]')?.dataset.document;if(documentId){void action({action:'library-document',id:documentId});}
 const memory=target.closest<HTMLElement>('[data-memory]')?.dataset.memory;if(memory){selectedProposal='';void action({action:'library-memory',id:memory});}
 const chunk=target.closest<HTMLElement>('[data-chunk]')?.dataset.chunk;if(chunk){void action({action:'library-chunk',id:chunk});}
 const proposal=target.closest<HTMLElement>('[data-proposal]')?.dataset.proposal;if(proposal){selectedProposal=proposal;stamp='';render();}
 const conversation=target.closest<HTMLElement>('[data-conversation]')?.dataset.conversation;if(conversation)void action({action:'library-conversation',id:conversation});
 if(target.closest('#documents-more'))void action({action:'library-documents',query:v.documents.query,more:true});
 if(target.closest('#search-more')&&v.search.value)void action({action:'library-search',kind:v.search.value.kind,query:v.search.value.query,mode:v.search.value.mode,more:true});
 if(target.closest('#document-citations'))void action({action:'library-citations'});
 if(target.closest('#document-stance'))void action({action:'library-stance',claim:$<HTMLTextAreaElement>('#document-claim').value});
 if(target.closest('#memory-invalidate')&&v.memory.value)void action({action:'library-maintain',kind:'invalidate',identity:memoryIdentity(v.memory.value),reason:$<HTMLTextAreaElement>('#memory-reason').value});
 const resolution=target.closest<HTMLElement>('[data-resolve]')?.dataset.resolve;if(resolution){const p=v.proposals.value?.find(row=>row.id===selectedProposal);if(p)void action({action:'library-maintain',kind:'resolve',identity:libraryIdentity(p),accept:resolution==='true',reason:$<HTMLTextAreaElement>('#proposal-reason').value});}
 const maintenance=target.closest<HTMLElement>('[data-maintain]')?.dataset.maintain;if(maintenance==='reembed'||maintenance==='reconsider')void action({action:'library-maintain',kind:maintenance,identity:libraryIdentity({project:v.project}),reason:''});
 const link=target.closest<HTMLElement>('[data-web-link]')?.dataset.webLink;if(link){event.preventDefault();void action({action:'open-link',url:link});}
});
window.plowshare.subscribe(update);void window.plowshare.request({action:'bootstrap'}).then(reply=>update(reply.state));
