package io.aeyer.plowshare.server.search;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Locale;
import org.junit.jupiter.api.Test;

/**
 * {@link QueryKey} carries no dependency worth a container — it is a pure function of a string and
 * an int — so unlike {@link ResultSetStoreTest} this needs no database at all.
 */
class QueryKeyTest {

  @Test
  void whitespace_and_case_do_not_make_a_different_search() {
    assertEquals(QueryKey.of("plowshare harness", 25), QueryKey.of("  Plowshare   Harness ", 25));
  }

  @Test
  void a_different_max_is_a_different_search_because_it_bought_a_different_set() {
    assertNotEquals(QueryKey.of("q", 25), QueryKey.of("q", 50));
  }

  @Test
  void the_key_is_a_sha_256_and_carries_none_of_the_query() {
    assertTrue(QueryKey.of("secret question", 10).matches("^[0-9a-f]{64}$"));
  }

  /**
   * The key does not depend on where the machine thinks it is.
   *
   * <p>Turkish, specifically, because it is the locale where {@code toLowerCase()} without an
   * argument actually differs: {@code "WIKI"} folds to {@code "wıkı"} with dotless i. A server
   * booted with {@code -Duser.language=tr} would hash every mixed-case query differently from every
   * other server, and from itself before the locale changed — with no error anywhere, just page 2
   * never finding page 1's set.
   *
   * <p>Asserted against the key computed under the <b>default</b> locale rather than against a
   * hardcoded digest: a literal would have to be regenerated by hand if the normalisation
   * legitimately changed, and it would then pin the digest instead of the property. What is being
   * measured is that the two agree, which is the whole claim.
   *
   * <p>The locale is restored in a finally block. JUnit runs test classes in one JVM, and a leaked
   * default locale would reach every test after this one — including any that formats a number.
   */
  @Test
  void the_default_locale_does_not_change_the_key() {
    String underDefault = QueryKey.of("WIKI Plowshare", 25);
    Locale before = Locale.getDefault();
    try {
      Locale.setDefault(Locale.forLanguageTag("tr"));
      // The fixture has to contain something for the locale to act on:
      // an 'I' is the one character Turkish folds differently, so a
      // query without one would pass against toLowerCase() too.
      assertTrue("WIKI Plowshare".indexOf('I') >= 0, "the fixture has no I to fold");
      assertEquals(underDefault, QueryKey.of("WIKI Plowshare", 25));
    } finally {
      Locale.setDefault(before);
    }
  }
}
